"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

import dj_database_url
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    'SECRET_KEY', 'django-insecure-56oz@^21iq7n5%(z7q-eltj82vx0q5k+v4exa!7jp6wn=e(x&&'
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = [h.strip() for h in os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',') if h.strip()]

# Railway injects this automatically once the service has a public domain.
_railway_domain = os.environ.get('RAILWAY_PUBLIC_DOMAIN')
if _railway_domain:
    ALLOWED_HOSTS.append(_railway_domain)

# Django checks the Origin header on unsafe requests (e.g. admin login POSTs)
# against this list. Without it, HTTPS requests through Railway's proxy fail
# CSRF verification even with a valid token.
CSRF_TRUSTED_ORIGINS = [
    o.strip() for o in os.environ.get('CSRF_TRUSTED_ORIGINS', '').split(',') if o.strip()
]
if _railway_domain:
    CSRF_TRUSTED_ORIGINS.append(f'https://{_railway_domain}')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'accounts',
    'billing',
    'professors',
    'schools',
    'search',
]

AUTH_USER_MODEL = 'accounts.User'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ALLOWED_ORIGINS = [
    o.strip() for o in os.environ.get('CORS_ALLOWED_ORIGINS', 'http://localhost:5173').split(',') if o.strip()
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}

# Verification code emails. Sent via Resend's SMTP relay once RESEND_API_KEY is set
# (e.g. in Railway's env vars); otherwise falls back to printing to the console,
# which is what local dev has always done.
RESEND_API_KEY = os.environ.get('RESEND_API_KEY', '')
# When RESEND_API_KEY is set, utils.send_code_email uses Resend's HTTP API directly
# (avoids port 587 which Railway blocks). Console backend is used for local dev.
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

DEFAULT_FROM_EMAIL = os.environ.get(
    'DEFAULT_FROM_EMAIL', 'KnowBeforeYouGo <noreply@knowbeforeyougobahamas.com>'
)

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# Railway's Postgres plugin injects DATABASE_URL automatically. Falls back to the
# local SQLite file when it's absent (e.g. local dev, or before Postgres is added).
_database_url = os.environ.get('DATABASE_URL')
if _database_url:
    DATABASES = {'default': dj_database_url.parse(_database_url, conn_max_age=600)}
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}

# Built React app (`cd frontend && npm run build` outputs straight here — see
# vite.config.js). Whitenoise serves its assets/ directory etc. from the site root,
# separately from STATIC_ROOT above. Guarded so local `runserver` works fine
# whether or not the frontend has been built.
FRONTEND_DIST_DIR = BASE_DIR / 'frontend_dist'
if FRONTEND_DIST_DIR.exists():
    WHITENOISE_ROOT = FRONTEND_DIST_DIR

# Payoneer Checkout (billing). Blank until set in .env — checkout/notification
# views fail gracefully with a clear error until they're configured.
# PAYONEER_API_USERNAME / PAYONEER_PAYMENT_TOKEN come from the merchant portal:
# Integration > API access > Generate token.
# PAYONEER_DIVISION is your store/division code, also from that portal.
# PAYONEER_NOTIFICATION_TOKEN is a secret we make up ourselves and attach to the
# notificationUrl, so we can confirm incoming notifications actually came from us
# asking Payoneer to call back (Payoneer Checkout has no signature/HMAC scheme).
PAYONEER_API_USERNAME = os.environ.get('PAYONEER_API_USERNAME', '')
PAYONEER_PAYMENT_TOKEN = os.environ.get('PAYONEER_PAYMENT_TOKEN', '')
PAYONEER_DIVISION = os.environ.get('PAYONEER_DIVISION', '')
PAYONEER_NOTIFICATION_TOKEN = os.environ.get('PAYONEER_NOTIFICATION_TOKEN', '')
# Sandbox by default — switch to the live base URL Payoneer gives you when your
# account is approved (confirm the exact host in the merchant portal; don't assume
# api.live.oscato.com without checking, the sandbox host is the only one that's
# been confirmed against current docs).
PAYONEER_API_BASE_URL = os.environ.get('PAYONEER_API_BASE_URL', 'https://api.sandbox.oscato.com')
# Customer's country code for the LIST request. We don't currently collect this from
# UB students, so default to the Bahamas; override via env if that's wrong.
PAYONEER_DEFAULT_COUNTRY = os.environ.get('PAYONEER_DEFAULT_COUNTRY', 'BS')
FRONTEND_URL = os.environ.get('FRONTEND_URL', 'http://localhost:5173')

GOOGLE_CLIENT_ID = os.environ.get('GOOGLE_CLIENT_ID', '')
