# Generated by Django 6.0.6 on 2026-06-30 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='stripe_payment_intent_id',
            new_name='payoneer_short_id',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='stripe_checkout_session_id',
            new_name='payoneer_transaction_id',
        ),
    ]
