"""
Django management command: seed_ub_courses

Adds all University of The Bahamas courses that are not already in the
database (matched by course code). Safe to run multiple times — existing
records are never overwritten, only missing ones are inserted.

Usage:
    python manage.py seed_ub_courses
"""

from django.core.management.base import BaseCommand

from professors.models import Course

COURSES = [
    # ──────────────────────────────────────────────
    # SCHOOL OF PURE AND APPLIED SCIENCES
    # ──────────────────────────────────────────────

    # Biology
    ("BIO102", "Introduction to Ecology", "School of Pure and Applied Sciences",
     "An introduction to the principles of ecology, including population, community, and ecosystem dynamics with a Caribbean focus."),
    ("BIO201", "Cell Biology", "School of Pure and Applied Sciences",
     "Study of cell structure, function, and metabolism, including molecular mechanisms of cell division and signalling."),
    ("BIO202", "Genetics", "School of Pure and Applied Sciences",
     "Principles of heredity including Mendelian genetics, molecular genetics, gene regulation, and genomics."),
    ("BIO211", "Biology Laboratory I", "School of Pure and Applied Sciences",
     "Laboratory exercises supporting Biology 101, covering microscopy, cell studies, and basic biological techniques."),
    ("BIO212", "Biology Laboratory II", "School of Pure and Applied Sciences",
     "Laboratory exercises supporting Biology 102, covering field ecology, dissection, and experimental methods."),
    ("BIO301", "Microbiology", "School of Pure and Applied Sciences",
     "Study of microorganisms including bacteria, viruses, fungi, and protozoa, with emphasis on their roles in health and the environment."),
    ("BIO302", "Ecology", "School of Pure and Applied Sciences",
     "Relationships between organisms and their environments, energy flow, nutrient cycling, and conservation ecology."),
    ("BIO303", "Anatomy and Physiology I", "School of Pure and Applied Sciences",
     "Structure and function of the human body: skeletal, muscular, nervous, and endocrine systems."),
    ("BIO304", "Anatomy and Physiology II", "School of Pure and Applied Sciences",
     "Continuation of Anatomy and Physiology I: cardiovascular, respiratory, digestive, urinary, and reproductive systems."),
    ("BIO305", "Marine Biology", "School of Pure and Applied Sciences",
     "Biology of marine organisms and ecosystems, with emphasis on the coastal and reef environments of The Bahamas."),
    ("BIO401", "Molecular Biology", "School of Pure and Applied Sciences",
     "Advanced study of DNA replication, transcription, translation, and gene regulation at the molecular level."),
    ("BIO402", "Evolutionary Biology", "School of Pure and Applied Sciences",
     "Mechanisms of evolution, including natural selection, genetic drift, speciation, and the history of life on Earth."),
    ("BIO403", "Immunology", "School of Pure and Applied Sciences",
     "Structure and function of the immune system; innate and adaptive immunity; clinical applications."),
    ("BIO404", "Parasitology", "School of Pure and Applied Sciences",
     "Biology, life cycles, and control of parasites of medical and veterinary importance in the Caribbean."),
    ("BIO498", "Senior Thesis I: Biology", "School of Pure and Applied Sciences",
     "Independent research project under faculty supervision; literature review and research proposal."),
    ("BIO499", "Senior Thesis II: Biology", "School of Pure and Applied Sciences",
     "Completion of the independent research project; data analysis, thesis writing, and oral presentation."),

    # Chemistry
    ("CHEM101", "General Chemistry I", "School of Pure and Applied Sciences",
     "Principles of chemistry: atomic structure, chemical bonding, stoichiometry, gases, and thermochemistry."),
    ("CHEM102", "General Chemistry II", "School of Pure and Applied Sciences",
     "Continuation of General Chemistry I: solutions, kinetics, equilibrium, acids and bases, electrochemistry."),
    ("CHEM111", "General Chemistry Laboratory I", "School of Pure and Applied Sciences",
     "Laboratory exercises supporting General Chemistry I; qualitative and quantitative analysis techniques."),
    ("CHEM112", "General Chemistry Laboratory II", "School of Pure and Applied Sciences",
     "Laboratory exercises supporting General Chemistry II; synthesis, titration, and spectroscopy."),
    ("CHEM201", "Organic Chemistry I", "School of Pure and Applied Sciences",
     "Structure, properties, and reactions of organic compounds: alkanes, alkenes, alkynes, and aromatic compounds."),
    ("CHEM202", "Organic Chemistry II", "School of Pure and Applied Sciences",
     "Continuation of Organic Chemistry I: carbonyl compounds, amines, polymers, carbohydrates, and spectroscopic analysis."),
    ("CHEM211", "Organic Chemistry Laboratory I", "School of Pure and Applied Sciences",
     "Synthesis and characterisation of organic compounds using modern laboratory techniques."),
    ("CHEM212", "Organic Chemistry Laboratory II", "School of Pure and Applied Sciences",
     "Advanced organic synthesis and spectroscopic identification of compounds."),
    ("CHEM301", "Analytical Chemistry", "School of Pure and Applied Sciences",
     "Principles and methods of chemical analysis including gravimetry, titrimetry, and instrumental methods."),
    ("CHEM302", "Physical Chemistry I", "School of Pure and Applied Sciences",
     "Thermodynamics, chemical equilibria, and electrochemistry from a physical chemistry perspective."),
    ("CHEM303", "Physical Chemistry II", "School of Pure and Applied Sciences",
     "Quantum mechanics, spectroscopy, statistical mechanics, and reaction kinetics."),
    ("CHEM304", "Inorganic Chemistry", "School of Pure and Applied Sciences",
     "Properties and reactions of inorganic compounds; coordination chemistry and organometallics."),
    ("CHEM401", "Biochemistry I", "School of Pure and Applied Sciences",
     "Chemistry of biological macromolecules: proteins, nucleic acids, carbohydrates, and lipids."),
    ("CHEM402", "Biochemistry II", "School of Pure and Applied Sciences",
     "Metabolism, enzyme kinetics, biosynthetic pathways, and molecular genetics from a biochemical viewpoint."),
    ("CHEM403", "Environmental Chemistry", "School of Pure and Applied Sciences",
     "Chemistry of natural waters, atmosphere, and soils; pollution analysis and environmental remediation."),
    ("CHEM498", "Senior Thesis I: Chemistry", "School of Pure and Applied Sciences",
     "Independent chemistry research project; literature review and experimental design."),
    ("CHEM499", "Senior Thesis II: Chemistry", "School of Pure and Applied Sciences",
     "Completion of the chemistry research project; data analysis, thesis writing, and oral defence."),

    # Physics
    ("PHYS101", "General Physics I", "School of Pure and Applied Sciences",
     "Mechanics, kinematics, Newton's laws, work and energy, momentum, and rotational motion."),
    ("PHYS102", "General Physics II", "School of Pure and Applied Sciences",
     "Waves, sound, heat, thermodynamics, electricity, magnetism, and optics."),
    ("PHYS111", "General Physics Laboratory I", "School of Pure and Applied Sciences",
     "Laboratory experiments supporting General Physics I; measurement, motion, and energy."),
    ("PHYS112", "General Physics Laboratory II", "School of Pure and Applied Sciences",
     "Laboratory experiments supporting General Physics II; electricity, circuits, waves, and optics."),
    ("PHYS201", "Modern Physics", "School of Pure and Applied Sciences",
     "Relativity, quantum mechanics, atomic and nuclear physics, and an introduction to particle physics."),
    ("PHYS301", "Classical Mechanics", "School of Pure and Applied Sciences",
     "Newtonian mechanics, Lagrangian and Hamiltonian formulations, oscillations, and rigid body dynamics."),
    ("PHYS302", "Electromagnetism", "School of Pure and Applied Sciences",
     "Maxwell's equations, electric and magnetic fields, electromagnetic waves, and radiation."),
    ("PHYS303", "Thermodynamics and Statistical Mechanics", "School of Pure and Applied Sciences",
     "Laws of thermodynamics, entropy, statistical ensembles, and applications to physical systems."),
    ("PHYS401", "Quantum Mechanics", "School of Pure and Applied Sciences",
     "Wave functions, the Schrödinger equation, quantum operators, angular momentum, and hydrogen atom."),
    ("PHYS402", "Optics", "School of Pure and Applied Sciences",
     "Geometrical and physical optics, interference, diffraction, polarisation, and laser physics."),
    ("PHYS498", "Senior Thesis I: Physics", "School of Pure and Applied Sciences",
     "Independent physics research project; literature review and experimental or computational design."),
    ("PHYS499", "Senior Thesis II: Physics", "School of Pure and Applied Sciences",
     "Completion of the physics research project; analysis, writing, and oral defence."),

    # Environmental Science
    ("ENVS101", "Introduction to Environmental Science", "School of Pure and Applied Sciences",
     "Overview of Earth's natural systems and the human impacts on air, water, land, and biodiversity."),
    ("ENVS102", "Environmental Issues in The Bahamas", "School of Pure and Applied Sciences",
     "Current environmental challenges facing The Bahamas: coastal erosion, coral bleaching, pollution, and climate change."),
    ("ENVS201", "Ecology", "School of Pure and Applied Sciences",
     "Ecosystem structure and function, energy flow, nutrient cycles, population dynamics, and community ecology."),
    ("ENVS202", "Environmental Chemistry", "School of Pure and Applied Sciences",
     "Chemical processes in the environment; fate and transport of pollutants in air, water, and soil."),
    ("ENVS301", "Conservation Biology", "School of Pure and Applied Sciences",
     "Principles of conservation biology; biodiversity, habitat loss, invasive species, and protected areas management."),
    ("ENVS302", "Marine Ecology", "School of Pure and Applied Sciences",
     "Ecology of marine ecosystems with emphasis on coral reefs, mangroves, and seagrass beds of The Bahamas."),
    ("ENVS303", "Environmental Policy and Law", "School of Pure and Applied Sciences",
     "National and international environmental law and policy frameworks; Bahamian environmental legislation."),
    ("ENVS304", "Geographic Information Systems", "School of Pure and Applied Sciences",
     "Introduction to GIS software and spatial data analysis for environmental applications."),
    ("ENVS401", "Climate Change Science and Impacts", "School of Pure and Applied Sciences",
     "The science of climate change, projected impacts on small island developing states, and adaptation strategies."),
    ("ENVS402", "Coastal and Island Ecosystems", "School of Pure and Applied Sciences",
     "Structure, function, and management of coastal ecosystems unique to island environments."),
    ("ENVS403", "Environmental Impact Assessment", "School of Pure and Applied Sciences",
     "Methods and procedures for assessing the environmental impact of development projects."),
    ("ENVS498", "Senior Thesis I: Environmental Science", "School of Pure and Applied Sciences",
     "Independent environmental research project; proposal development and literature review."),
    ("ENVS499", "Senior Thesis II: Environmental Science", "School of Pure and Applied Sciences",
     "Completion of the environmental research project; field work, analysis, and thesis writing."),

    # Marine Science
    ("MARS101", "Introduction to Marine Science", "School of Pure and Applied Sciences",
     "Overview of the marine environment: ocean chemistry, physical oceanography, and marine organisms."),
    ("MARS201", "Marine Biology", "School of Pure and Applied Sciences",
     "Diversity, physiology, and ecology of marine organisms from phytoplankton to marine mammals."),
    ("MARS202", "Oceanography", "School of Pure and Applied Sciences",
     "Physical, chemical, geological, and biological oceanography; ocean circulation and climate."),
    ("MARS301", "Coral Reef Ecology", "School of Pure and Applied Sciences",
     "Structure, function, biodiversity, and conservation of coral reef ecosystems in the Caribbean."),
    ("MARS302", "Fisheries Science", "School of Pure and Applied Sciences",
     "Fish biology, population dynamics, stock assessment, and sustainable fisheries management."),
    ("MARS303", "Marine Conservation", "School of Pure and Applied Sciences",
     "Threats to marine biodiversity and strategies for conservation, including marine protected areas."),
    ("MARS498", "Senior Thesis I: Marine Science", "School of Pure and Applied Sciences",
     "Independent marine science research; proposal, literature review, and research design."),
    ("MARS499", "Senior Thesis II: Marine Science", "School of Pure and Applied Sciences",
     "Completion of the marine science research project; data collection, analysis, and thesis defence."),

    # Statistics
    ("STAT201", "Introduction to Statistics", "School of Pure and Applied Sciences",
     "Descriptive statistics, probability, sampling distributions, hypothesis testing, and regression."),
    ("STAT202", "Probability and Statistics", "School of Pure and Applied Sciences",
     "Probability theory, random variables, distributions, and statistical inference."),
    ("STAT301", "Statistical Methods", "School of Pure and Applied Sciences",
     "Advanced statistical techniques: analysis of variance, non-parametric tests, and experimental design."),
    ("STAT302", "Regression Analysis", "School of Pure and Applied Sciences",
     "Simple and multiple regression, model diagnostics, variable selection, and logistic regression."),
    ("STAT401", "Mathematical Statistics", "School of Pure and Applied Sciences",
     "Theoretical foundations of statistical inference: estimation, hypothesis testing, and Bayesian methods."),
    ("STAT402", "Applied Statistics", "School of Pure and Applied Sciences",
     "Statistical computing, data analysis, and interpretation using modern statistical software."),

    # More Computer Science
    ("CS301", "Algorithms and Data Structures", "Computer Science",
     "Design and analysis of algorithms; sorting, searching, graph algorithms, and computational complexity."),
    ("CS302", "Computer Organization and Architecture", "Computer Science",
     "Digital logic, computer organisation, instruction sets, memory hierarchy, and I/O systems."),
    ("CS303", "Operating Systems", "Computer Science",
     "Process management, memory management, file systems, I/O, and concurrent programming."),
    ("CS304", "Database Systems", "Computer Science",
     "Relational database design, SQL, normalisation, query optimisation, and transaction management."),
    ("CS305", "Computer Networks", "Computer Science",
     "Network architecture, protocols, TCP/IP, routing, security, and wireless networks."),
    ("CS401", "Software Engineering", "Computer Science",
     "Software development lifecycle, requirements, design patterns, testing, and project management."),
    ("CS402", "Artificial Intelligence", "Computer Science",
     "Search algorithms, knowledge representation, machine learning, natural language processing, and robotics."),
    ("CS403", "Web Development", "Computer Science",
     "Modern web technologies: HTML, CSS, JavaScript, front-end frameworks, back-end APIs, and databases."),
    ("CS404", "Cybersecurity", "Computer Science",
     "Information security principles, cryptography, network security, ethical hacking, and security management."),
    ("CS498", "Senior Thesis I: Computer Science", "Computer Science",
     "Individual software development or research project; requirements gathering, design, and implementation planning."),
    ("CS499", "Senior Thesis II: Computer Science", "Computer Science",
     "Completion of the senior software project; implementation, testing, documentation, and presentation."),

    # More Mathematics
    ("MAT102", "Calculus II", "Mathematics",
     "Integration techniques, applications of integration, sequences, series, and polar coordinates."),
    ("MAT201", "Calculus III", "Mathematics",
     "Multivariable calculus: partial derivatives, multiple integrals, vector calculus, and theorems of Green, Stokes, and Gauss."),
    ("MAT202", "Linear Algebra", "Mathematics",
     "Vectors, matrices, systems of equations, determinants, eigenvalues, and vector spaces."),
    ("MAT301", "Differential Equations", "Mathematics",
     "Ordinary differential equations, Laplace transforms, series solutions, and systems of ODEs."),
    ("MAT302", "Discrete Mathematics", "Mathematics",
     "Logic, sets, functions, relations, combinatorics, graph theory, and mathematical proof techniques."),
    ("MAT303", "Number Theory", "Mathematics",
     "Divisibility, prime numbers, congruences, Diophantine equations, and cryptographic applications."),
    ("MAT401", "Abstract Algebra", "Mathematics",
     "Groups, rings, fields, homomorphisms, and an introduction to Galois theory."),
    ("MAT402", "Real Analysis", "Mathematics",
     "Rigorous treatment of limits, continuity, differentiation, integration, and sequences of functions."),
    ("MAT403", "Numerical Methods", "Mathematics",
     "Numerical solutions to equations, interpolation, numerical integration and differentiation, and ODEs."),
    ("MAT404", "Probability Theory", "Mathematics",
     "Axiomatic probability, random variables, expectation, distributions, and limit theorems."),
    ("MAT498", "Senior Thesis I: Mathematics", "Mathematics",
     "Independent mathematics research project; topic selection, literature review, and outline."),
    ("MAT499", "Senior Thesis II: Mathematics", "Mathematics",
     "Completion of the mathematics research project; proof development, writing, and oral defence."),

    # ──────────────────────────────────────────────
    # SCHOOL OF SOCIAL AND EDUCATIONAL STUDIES
    # ──────────────────────────────────────────────

    # Psychology
    ("PSYC101", "Introduction to Psychology", "School of Social and Educational Studies",
     "Survey of psychology's major subfields: biological bases of behaviour, learning, cognition, development, personality, and social psychology."),
    ("PSYC102", "Research Methods in Psychology", "School of Social and Educational Studies",
     "Scientific method in psychology; experimental and non-experimental designs, statistics, and ethical guidelines."),
    ("PSYC201", "Developmental Psychology", "School of Social and Educational Studies",
     "Human development from conception through old age, including cognitive, social, and emotional development."),
    ("PSYC202", "Abnormal Psychology", "School of Social and Educational Studies",
     "Classification, causes, and treatment of psychological disorders; DSM framework and therapeutic approaches."),
    ("PSYC203", "Social Psychology", "School of Social and Educational Studies",
     "How thoughts, feelings, and behaviours are influenced by others; attitudes, conformity, aggression, and helping."),
    ("PSYC204", "Biological Psychology", "School of Social and Educational Studies",
     "Neuroanatomy, neurotransmitters, and the biological bases of behaviour, emotion, and mental disorders."),
    ("PSYC301", "Cognitive Psychology", "School of Social and Educational Studies",
     "Mental processes involved in perception, attention, memory, language, thinking, and problem solving."),
    ("PSYC302", "Personality Psychology", "School of Social and Educational Studies",
     "Major theories of personality; trait, psychodynamic, humanistic, and social-cognitive approaches."),
    ("PSYC303", "Health Psychology", "School of Social and Educational Studies",
     "Psychological factors in health and illness; stress, coping, chronic disease, and health promotion."),
    ("PSYC304", "Counselling Theories", "School of Social and Educational Studies",
     "Major theories and approaches in professional counselling; person-centred, CBT, and psychodynamic models."),
    ("PSYC305", "Industrial/Organisational Psychology", "School of Social and Educational Studies",
     "Application of psychological principles to the workplace: selection, motivation, leadership, and organisational behaviour."),
    ("PSYC306", "Community Psychology", "School of Social and Educational Studies",
     "Psychological perspectives on community life, prevention, empowerment, and social change."),
    ("PSYC401", "Advanced Research Methods", "School of Social and Educational Studies",
     "Advanced quantitative and qualitative research designs, multi-variate analysis, and research ethics."),
    ("PSYC402", "Psychological Assessment", "School of Social and Educational Studies",
     "Principles of psychological testing; intelligence, personality, and neuropsychological assessments."),
    ("PSYC498", "Senior Thesis I: Psychology", "School of Social and Educational Studies",
     "Independent psychological research project; topic selection, literature review, and methodology."),
    ("PSYC499", "Senior Thesis II: Psychology", "School of Social and Educational Studies",
     "Completion of the psychology research project; data collection, analysis, write-up, and presentation."),

    # Sociology
    ("SOCI101", "Introduction to Sociology", "School of Social and Educational Studies",
     "Sociological perspectives on social structure, culture, socialisation, stratification, and social change."),
    ("SOCI102", "Social Problems", "School of Social and Educational Studies",
     "Analysis of major social problems in The Bahamas and the Caribbean: poverty, crime, inequality, and discrimination."),
    ("SOCI201", "Cultural Anthropology", "School of Social and Educational Studies",
     "Introduction to cultural anthropology: culture, kinship, religion, economic systems, and globalisation."),
    ("SOCI202", "Caribbean Sociology", "School of Social and Educational Studies",
     "Social structures and processes unique to the Caribbean; slavery's legacy, identity, and development challenges."),
    ("SOCI203", "Race, Ethnicity, and Society", "School of Social and Educational Studies",
     "Sociological analysis of race and ethnicity; prejudice, discrimination, and multicultural societies."),
    ("SOCI204", "Gender and Society", "School of Social and Educational Studies",
     "Gender as a social construct; gender roles, feminism, masculinity, and gender-based inequality."),
    ("SOCI301", "Sociological Theory", "School of Social and Educational Studies",
     "Classical and contemporary sociological theory: Marx, Weber, Durkheim, Parsons, and contemporary theorists."),
    ("SOCI302", "Research Methods in Sociology", "School of Social and Educational Studies",
     "Quantitative and qualitative research methods; surveys, interviews, ethnography, and content analysis."),
    ("SOCI303", "Sociology of the Family", "School of Social and Educational Studies",
     "Family structures, roles, and dynamics; marriage, divorce, parenting, and family policy."),
    ("SOCI304", "Deviance and Social Control", "School of Social and Educational Studies",
     "Theories of deviant behaviour; crime, stigma, and social control mechanisms."),
    ("SOCI401", "Social Stratification", "School of Social and Educational Studies",
     "Systems of inequality: class, status, and power; social mobility in the Caribbean context."),
    ("SOCI402", "Urban Sociology", "School of Social and Educational Studies",
     "Urban social structures, community life, urbanisation, and development in the Caribbean."),
    ("SOCI403", "Sociology of Religion", "School of Social and Educational Studies",
     "The social dimensions of religion; religious institutions, movements, and religion's role in Caribbean society."),
    ("SOCI498", "Senior Thesis I: Sociology", "School of Social and Educational Studies",
     "Independent sociological research project; research question formulation, literature review, and methodology."),
    ("SOCI499", "Senior Thesis II: Sociology", "School of Social and Educational Studies",
     "Completion of the sociology research project; fieldwork, data analysis, and thesis writing."),

    # Political Science
    ("POLI101", "Introduction to Political Science", "School of Social and Educational Studies",
     "Foundations of political science; political systems, ideologies, institutions, and political behaviour."),
    ("POLI102", "Introduction to Political Thought", "School of Social and Educational Studies",
     "History of political philosophy from the ancient Greeks to the modern era."),
    ("POLI201", "Bahamian Government and Politics", "School of Social and Educational Studies",
     "The Constitution, Parliament, the executive, the judiciary, and political parties of The Bahamas."),
    ("POLI202", "Caribbean Politics", "School of Social and Educational Studies",
     "Political systems and governance challenges across the Caribbean; CARICOM and regional integration."),
    ("POLI203", "International Relations", "School of Social and Educational Studies",
     "Theories and issues in international relations; diplomacy, international organisations, and global governance."),
    ("POLI204", "Comparative Politics", "School of Social and Educational Studies",
     "Comparative analysis of political systems, elections, parties, and democratic institutions worldwide."),
    ("POLI301", "Political Theory", "School of Social and Educational Studies",
     "Normative political theory: justice, liberty, equality, democracy, and rights."),
    ("POLI302", "Research Methods in Political Science", "School of Social and Educational Studies",
     "Quantitative and qualitative research design for political analysis; surveys, case studies, and statistical methods."),
    ("POLI303", "Public Administration", "School of Social and Educational Studies",
     "Principles of public administration; bureaucracy, public policy implementation, and government management."),
    ("POLI304", "Public Policy", "School of Social and Educational Studies",
     "Policy-making processes; agenda-setting, policy design, implementation, and evaluation."),
    ("POLI401", "Global Politics", "School of Social and Educational Studies",
     "Globalisation, global governance, transnational actors, and emerging issues in world politics."),
    ("POLI402", "Caribbean Foreign Policy", "School of Social and Educational Studies",
     "Foreign policy challenges of small Caribbean states; bilateral and multilateral relations."),
    ("POLI498", "Senior Thesis I: Political Science", "School of Social and Educational Studies",
     "Independent political science research project; topic selection, literature review, and methodology."),
    ("POLI499", "Senior Thesis II: Political Science", "School of Social and Educational Studies",
     "Completion of the political science research project; analysis, writing, and oral defence."),

    # History
    ("HIST101", "History of The Bahamas", "School of Social and Educational Studies",
     "The Bahamas from the Lucayan era through colonial rule, emancipation, independence, and nationhood."),
    ("HIST102", "Caribbean History", "School of Social and Educational Studies",
     "History of the Caribbean from indigenous peoples through colonialism, slavery, emancipation, and independence."),
    ("HIST201", "World History to 1500", "School of Social and Educational Studies",
     "Major developments in human civilisation from ancient times through the late medieval period."),
    ("HIST202", "World History from 1500", "School of Social and Educational Studies",
     "Global history from the Age of Exploration through the twentieth century; colonialism, revolution, and globalisation."),
    ("HIST203", "African History", "School of Social and Educational Studies",
     "History of Africa from ancient kingdoms through colonialism, independence, and contemporary challenges."),
    ("HIST204", "British History", "School of Social and Educational Studies",
     "Political, social, and cultural history of Britain and its relationship with its colonies."),
    ("HIST205", "American History", "School of Social and Educational Studies",
     "United States history from colonial origins through the twenty-first century; its impact on the Caribbean."),
    ("HIST301", "Slavery and Emancipation in the Caribbean", "School of Social and Educational Studies",
     "The transatlantic slave trade, plantation society, abolition, and the aftermath of emancipation."),
    ("HIST302", "The Atlantic World", "School of Social and Educational Studies",
     "Interconnections among Europe, Africa, and the Americas in the age of exploration and colonialism."),
    ("HIST303", "Social History of The Bahamas", "School of Social and Educational Studies",
     "Social life, culture, labour, religion, and everyday experience in Bahamian history."),
    ("HIST401", "Historiography", "School of Social and Educational Studies",
     "Theory and methodology of historical research; how historians write history."),
    ("HIST402", "Historical Research Methods", "School of Social and Educational Studies",
     "Archival research, oral history, use of primary sources, and historical writing."),
    ("HIST498", "Senior Thesis I: History", "School of Social and Educational Studies",
     "Independent history research project; archival research, literature review, and thesis outline."),
    ("HIST499", "Senior Thesis II: History", "School of Social and Educational Studies",
     "Completion of the history thesis; research, analysis, writing, and oral defence."),

    # Education
    ("EDUC101", "Introduction to Education", "School of Social and Educational Studies",
     "Overview of education as a profession; history, philosophy, and organisation of education in The Bahamas."),
    ("EDUC201", "Educational Psychology", "School of Social and Educational Studies",
     "Psychological principles applied to teaching and learning; motivation, development, and learning theories."),
    ("EDUC202", "Curriculum Development", "School of Social and Educational Studies",
     "Principles and practices of curriculum design, implementation, and evaluation for Bahamian schools."),
    ("EDUC203", "Teaching Methods: Secondary", "School of Social and Educational Studies",
     "Strategies and techniques for effective teaching in secondary school settings."),
    ("EDUC204", "Teaching Methods: Primary", "School of Social and Educational Studies",
     "Pedagogy, classroom management, and instructional strategies for primary school teachers."),
    ("EDUC205", "Foundations of Early Childhood Education", "School of Social and Educational Studies",
     "Developmental theory, curriculum, and best practices for teaching children aged birth to eight years."),
    ("EDUC301", "Assessment and Evaluation", "School of Social and Educational Studies",
     "Principles of classroom and programme assessment; formative and summative evaluation strategies."),
    ("EDUC302", "Special Education", "School of Social and Educational Studies",
     "Identification, assessment, and instructional strategies for students with diverse learning needs."),
    ("EDUC303", "Classroom Management", "School of Social and Educational Studies",
     "Strategies for creating and maintaining positive, productive learning environments."),
    ("EDUC304", "Inclusive Education", "School of Social and Educational Studies",
     "Principles and practices of inclusive schooling; diversity, differentiation, and collaboration."),
    ("EDUC401", "Educational Leadership", "School of Social and Educational Studies",
     "Leadership theories and practices for school administrators; school culture and change management."),
    ("EDUC402", "Education Policy", "School of Social and Educational Studies",
     "Analysis of national and regional education policy; education reform and governance in The Bahamas."),
    ("EDUC403", "Educational Technology", "School of Social and Educational Studies",
     "Integration of technology into classroom instruction; digital tools, e-learning, and media literacy."),
    ("EDUC404", "Student Teaching Practicum", "School of Social and Educational Studies",
     "Supervised teaching experience in an accredited school; observation, co-teaching, and solo teaching."),
    ("EDUC498", "Senior Thesis I: Education", "School of Social and Educational Studies",
     "Independent education research project; action research design and literature review."),
    ("EDUC499", "Senior Thesis II: Education", "School of Social and Educational Studies",
     "Completion of the education research project; data collection, analysis, and presentation."),

    # Social Work
    ("SOWK101", "Introduction to Social Work", "School of Social and Educational Studies",
     "History, values, ethics, and scope of the social work profession; social welfare in The Bahamas."),
    ("SOWK201", "Human Behaviour and the Social Environment", "School of Social and Educational Studies",
     "Systems and ecological theories applied to individual, family, group, and community behaviour."),
    ("SOWK202", "Social Welfare Policy", "School of Social and Educational Studies",
     "Development and analysis of social welfare policy and its impact on vulnerable populations in the Caribbean."),
    ("SOWK301", "Social Work Practice I: Individuals and Families", "School of Social and Educational Studies",
     "Generalist social work skills for working with individuals and families; assessment, planning, and intervention."),
    ("SOWK302", "Social Work Practice II: Groups and Communities", "School of Social and Educational Studies",
     "Group work theory and community organisation practice; facilitating change at the macro level."),
    ("SOWK303", "Social Work Research Methods", "School of Social and Educational Studies",
     "Research design and evidence-based practice in social work; quantitative, qualitative, and mixed methods."),
    ("SOWK401", "Child Welfare", "School of Social and Educational Studies",
     "Child protection systems, family preservation, foster care, and adoption policies in The Bahamas."),
    ("SOWK402", "Field Practicum I", "School of Social and Educational Studies",
     "Supervised field placement in a social service agency; application of theory to practice."),
    ("SOWK403", "Field Practicum II", "School of Social and Educational Studies",
     "Advanced supervised field placement with increased responsibility and reflective practice seminars."),
    ("SOWK498", "Senior Thesis I: Social Work", "School of Social and Educational Studies",
     "Independent social work research or policy analysis project; proposal and literature review."),
    ("SOWK499", "Senior Thesis II: Social Work", "School of Social and Educational Studies",
     "Completion of the social work research project; analysis, writing, and oral defence."),

    # Criminology
    ("CRIM101", "Introduction to Criminology", "School of Social and Educational Studies",
     "Theories of crime and criminal behaviour; the nature and extent of crime in The Bahamas and the Caribbean."),
    ("CRIM201", "The Criminal Justice System", "School of Social and Educational Studies",
     "Structure and operation of the criminal justice system: police, courts, and corrections."),
    ("CRIM202", "Juvenile Delinquency", "School of Social and Educational Studies",
     "Causes and consequences of juvenile delinquency; youth crime prevention and the juvenile justice system."),
    ("CRIM301", "Policing", "School of Social and Educational Studies",
     "History, organisation, and practice of policing; community policing and law enforcement reform."),
    ("CRIM302", "Corrections", "School of Social and Educational Studies",
     "History and philosophy of punishment; incarceration, probation, parole, and rehabilitation programmes."),
    ("CRIM303", "Criminal Law", "School of Social and Educational Studies",
     "Principles of criminal law; elements of crimes, defences, and the Bahamian criminal justice process."),
    ("CRIM401", "Crime Prevention", "School of Social and Educational Studies",
     "Situational and social crime prevention strategies; evidence-based programmes for reducing crime."),
    ("CRIM402", "Research Methods in Criminology", "School of Social and Educational Studies",
     "Quantitative and qualitative research methods applied to criminological questions."),
    ("CRIM498", "Senior Thesis I: Criminology", "School of Social and Educational Studies",
     "Independent criminological research project; research question, literature review, and methodology."),
    ("CRIM499", "Senior Thesis II: Criminology", "School of Social and Educational Studies",
     "Completion of the criminology research project; data analysis, writing, and oral defence."),

    # Geography
    ("GEOG101", "Introduction to Human Geography", "School of Social and Educational Studies",
     "Human geography concepts: population, migration, cultural landscapes, urbanisation, and globalisation."),
    ("GEOG102", "Physical Geography", "School of Social and Educational Studies",
     "Earth's physical systems: atmosphere, hydrosphere, lithosphere, and biosphere; weather, climate, and landforms."),
    ("GEOG201", "Bahamian and Caribbean Geography", "School of Social and Educational Studies",
     "Physical and human geography of The Bahamas and the wider Caribbean region."),
    ("GEOG202", "Economic Geography", "School of Social and Educational Studies",
     "Spatial patterns of economic activity; trade, industry, agriculture, and regional development."),
    ("GEOG301", "Geographic Information Systems", "School of Social and Educational Studies",
     "GIS principles, spatial data analysis, and mapping for social science applications."),
    ("GEOG302", "Population Geography", "School of Social and Educational Studies",
     "Population distribution, growth, migration, and demographic change with a Caribbean focus."),
    ("GEOG498", "Senior Thesis I: Geography", "School of Social and Educational Studies",
     "Independent geography research project; topic selection, field methodology, and literature review."),
    ("GEOG499", "Senior Thesis II: Geography", "School of Social and Educational Studies",
     "Completion of the geography research project; mapping, analysis, and thesis writing."),

    # ──────────────────────────────────────────────
    # SCHOOL OF NURSING
    # ──────────────────────────────────────────────
    ("NURS101", "Foundations of Nursing", "School of Nursing",
     "Nursing history, philosophy, and professional values; basic nursing care concepts and health assessment."),
    ("NURS102", "Nursing Theory and Conceptual Models", "School of Nursing",
     "Major nursing theories and conceptual frameworks that guide professional practice."),
    ("NURS111", "Nursing Skills Laboratory I", "School of Nursing",
     "Hands-on practice of fundamental nursing skills: vital signs, hygiene, medication administration basics."),
    ("NURS112", "Nursing Skills Laboratory II", "School of Nursing",
     "Advanced nursing skills: IV therapy, wound care, catheterisation, and sterile technique."),
    ("NURS201", "Adult Health Nursing I", "School of Nursing",
     "Nursing care of adults with common medical-surgical conditions; pathophysiology and evidence-based interventions."),
    ("NURS202", "Adult Health Nursing II", "School of Nursing",
     "Nursing care of adults with complex medical-surgical and critical conditions."),
    ("NURS203", "Mental Health Nursing", "School of Nursing",
     "Psychiatric nursing principles; therapeutic communication, psychopharmacology, and care of patients with mental illness."),
    ("NURS204", "Pediatric Nursing", "School of Nursing",
     "Nursing care of infants, children, and adolescents; growth, development, and family-centred care."),
    ("NURS205", "Pharmacology for Nurses", "School of Nursing",
     "Drug classifications, mechanisms of action, therapeutic uses, adverse effects, and nursing implications."),
    ("NURS206", "Pathophysiology", "School of Nursing",
     "Mechanisms of disease and altered physiological processes as a foundation for clinical nursing practice."),
    ("NURS301", "Maternal-Newborn Nursing", "School of Nursing",
     "Nursing care during pregnancy, labour, delivery, and the postpartum period; newborn assessment and care."),
    ("NURS302", "Community Health Nursing", "School of Nursing",
     "Population-focused nursing; epidemiology, health promotion, and community health assessment in The Bahamas."),
    ("NURS303", "Nursing Leadership and Management", "School of Nursing",
     "Leadership theories, team management, delegation, and quality improvement in nursing practice."),
    ("NURS304", "Nursing Research", "School of Nursing",
     "Evidence-based nursing practice; critical appraisal of research, research design, and application to clinical care."),
    ("NURS401", "Advanced Health Assessment", "School of Nursing",
     "Comprehensive physical examination, diagnostic reasoning, and health history for complex patient presentations."),
    ("NURS402", "Gerontological Nursing", "School of Nursing",
     "Nursing care of older adults; physiological changes of ageing, geriatric syndromes, and end-of-life care."),
    ("NURS403", "Clinical Practicum I", "School of Nursing",
     "Supervised clinical placement in an acute care facility; application of nursing skills and theory."),
    ("NURS404", "Clinical Practicum II", "School of Nursing",
     "Advanced supervised clinical placement across multiple specialities; professional role development."),
    ("NURS405", "Clinical Practicum III", "School of Nursing",
     "Senior-level clinical practicum; leadership, case management, and preceptored practice."),
    ("NURS498", "Senior Thesis I: Nursing", "School of Nursing",
     "Evidence-based capstone project; clinical question formulation, literature review, and proposal."),
    ("NURS499", "Senior Thesis II: Nursing", "School of Nursing",
     "Completion of the nursing capstone project; data collection, analysis, and oral presentation."),

    # ──────────────────────────────────────────────
    # TOURISM AND HOSPITALITY
    # (sometimes housed in School of Business)
    # ──────────────────────────────────────────────
    ("TOUR101", "Introduction to Tourism", "School of Business",
     "Overview of the global tourism industry; tourism systems, stakeholders, and The Bahamas' tourism economy."),
    ("TOUR201", "Tourism Management", "School of Business",
     "Management principles applied to tourism enterprises; planning, organising, and leading tourism operations."),
    ("TOUR202", "Ecotourism", "School of Business",
     "Principles and practice of ecotourism; sustainable tourism development in natural and cultural environments."),
    ("TOUR301", "Tourism Marketing", "School of Business",
     "Marketing strategies for tourism destinations and businesses; consumer behaviour and digital marketing."),
    ("TOUR302", "Sustainable Tourism Development", "School of Business",
     "Frameworks for developing tourism that minimises environmental impact and maximises community benefit."),
    ("TOUR303", "Heritage and Cultural Tourism", "School of Business",
     "Tourism based on cultural and natural heritage; interpretation, authenticity, and community involvement."),
    ("TOUR401", "Tourism Policy and Planning", "School of Business",
     "National and regional tourism policy; destination planning, governance, and the role of government."),
    ("TOUR402", "Tourism Economics", "School of Business",
     "Economic analysis of tourism; tourism demand, supply, multipliers, and the Bahamian tourism economy."),
    ("TOUR498", "Senior Thesis I: Tourism", "School of Business",
     "Independent tourism research project; research design and literature review."),
    ("TOUR499", "Senior Thesis II: Tourism", "School of Business",
     "Completion of the tourism research project; fieldwork, analysis, and presentation."),

    # Hotel, Restaurant, and Spa Management
    ("HRSM101", "Introduction to Hospitality Management", "School of Business",
     "Overview of the hospitality industry; hotels, restaurants, and resorts in The Bahamas and the Caribbean."),
    ("HRSM201", "Front Office Operations", "School of Business",
     "Reservations, check-in/check-out procedures, property management systems, and guest relations."),
    ("HRSM202", "Housekeeping Management", "School of Business",
     "Organisation and management of housekeeping departments in hotels and resorts."),
    ("HRSM203", "Food and Beverage Management", "School of Business",
     "Operations management for restaurants and food service; cost control, menu planning, and service standards."),
    ("HRSM204", "Lodging Management", "School of Business",
     "Strategic management of hotel and resort operations; revenue management, staffing, and quality control."),
    ("HRSM205", "Event Management", "School of Business",
     "Planning, organising, and executing meetings, conferences, weddings, and special events."),
    ("HRSM301", "Hospitality Law", "School of Business",
     "Legal aspects of the hospitality industry; liability, contracts, consumer protection, and licensing."),
    ("HRSM302", "Hospitality Marketing", "School of Business",
     "Marketing strategies for hotels and resorts; branding, digital marketing, and loyalty programmes."),
    ("HRSM303", "Resort and Spa Management", "School of Business",
     "Operations and management of resort and spa facilities; guest experience and wellness programming."),
    ("HRSM401", "Revenue Management", "School of Business",
     "Demand forecasting, pricing strategies, and yield management for hospitality businesses."),
    ("HRSM402", "Hospitality Financial Management", "School of Business",
     "Financial analysis, budgeting, and cost control specific to hospitality operations."),
    ("HRSM498", "Senior Thesis I: Hospitality Management", "School of Business",
     "Independent hospitality research or industry project; proposal and literature review."),
    ("HRSM499", "Senior Thesis II: Hospitality Management", "School of Business",
     "Completion of the hospitality research project; analysis, writing, and oral presentation."),

    # Culinary Arts
    ("CULA101", "Culinary Arts Fundamentals", "School of Business",
     "Basic culinary skills: knife techniques, cooking methods, sanitation, and kitchen safety."),
    ("CULA201", "Culinary Techniques", "School of Business",
     "Intermediate cooking techniques; sauces, stocks, braising, roasting, and baking fundamentals."),
    ("CULA202", "Bahamian and Caribbean Cuisine", "School of Business",
     "History, ingredients, and techniques of Bahamian and Caribbean culinary traditions."),
    ("CULA301", "Pastry and Baking Arts", "School of Business",
     "Artisan bread, cakes, pastries, and confectionery; classical and modern baking techniques."),
    ("CULA302", "International Cuisine", "School of Business",
     "Culinary traditions from around the world; techniques, ingredients, and cultural context."),
    ("CULA401", "Food and Beverage Business Operations", "School of Business",
     "Running a successful food service business; menu costing, staffing, marketing, and entrepreneurship."),

    # ──────────────────────────────────────────────
    # SCHOOL OF LIBERAL AND FINE ARTS
    # (Philosophy, Theatre, Humanities, Religious Studies)
    # ──────────────────────────────────────────────

    # Philosophy
    ("PHIL101", "Introduction to Philosophy", "School of Liberal and Fine Arts",
     "Central questions of philosophy: knowledge, reality, ethics, and the meaning of existence."),
    ("PHIL102", "Critical Thinking and Logic", "School of Liberal and Fine Arts",
     "Principles of sound reasoning; argument analysis, logical fallacies, and formal and informal logic."),
    ("PHIL201", "Ethics", "School of Liberal and Fine Arts",
     "Normative ethical theories — utilitarianism, deontology, virtue ethics — and their application to moral problems."),
    ("PHIL202", "Philosophy of Religion", "School of Liberal and Fine Arts",
     "Philosophical analysis of religious belief; arguments for and against the existence of God; faith and reason."),
    ("PHIL203", "Political Philosophy", "School of Liberal and Fine Arts",
     "Philosophical foundations of political authority, justice, rights, democracy, and the social contract."),
    ("PHIL301", "Philosophy of Mind", "School of Liberal and Fine Arts",
     "The nature of mind and consciousness; dualism, physicalism, functionalism, and artificial intelligence."),
    ("PHIL302", "Epistemology", "School of Liberal and Fine Arts",
     "Theory of knowledge; the nature of belief, justification, truth, and scepticism."),
    ("PHIL401", "Metaphysics", "School of Liberal and Fine Arts",
     "Fundamental questions about reality: existence, identity, causation, space, and time."),
    ("PHIL402", "Philosophy of Science", "School of Liberal and Fine Arts",
     "Philosophical analysis of scientific method, explanation, theory, and the demarcation problem."),
    ("PHIL498", "Senior Thesis I: Philosophy", "School of Liberal and Fine Arts",
     "Independent philosophical research project; topic selection and argumentative outline."),
    ("PHIL499", "Senior Thesis II: Philosophy", "School of Liberal and Fine Arts",
     "Completion of the philosophy thesis; argument development, writing, and oral defence."),

    # Theatre Arts
    ("THEA101", "Introduction to Theatre Arts", "School of Communication and Creative Arts",
     "History, theory, and appreciation of theatre; reading plays and attending live performances."),
    ("THEA201", "Acting I", "School of Communication and Creative Arts",
     "Fundamental acting techniques; voice, movement, characterisation, and scene study."),
    ("THEA202", "Stagecraft", "School of Communication and Creative Arts",
     "Technical aspects of theatre production: set design, lighting, sound, and stage management."),
    ("THEA203", "Script Analysis", "School of Communication and Creative Arts",
     "Analytical tools for reading and interpreting dramatic texts for performance."),
    ("THEA301", "Directing", "School of Communication and Creative Arts",
     "Principles and practice of theatrical direction; script interpretation, staging, and rehearsal process."),
    ("THEA302", "Playwriting", "School of Communication and Creative Arts",
     "Craft of writing for the stage; dramatic structure, dialogue, character, and the development of original work."),
    ("THEA303", "Caribbean Theatre and Performance", "School of Communication and Creative Arts",
     "Theatre traditions and performance practices of the Caribbean; folk forms, carnival, and contemporary drama."),
    ("THEA401", "Advanced Acting", "School of Communication and Creative Arts",
     "Advanced techniques in classical and contemporary performance styles."),
    ("THEA498", "Senior Thesis I: Theatre Arts", "School of Communication and Creative Arts",
     "Independent theatre project or research; directing, writing, or historical study."),
    ("THEA499", "Senior Thesis II: Theatre Arts", "School of Communication and Creative Arts",
     "Completion of the theatre arts project; public performance or written thesis and defence."),

    # Religious Studies
    ("RELI101", "Introduction to Religious Studies", "School of Liberal and Fine Arts",
     "Academic study of religion; methods, key concepts, and introduction to major world religions."),
    ("RELI201", "World Religions", "School of Liberal and Fine Arts",
     "Comparative study of Hinduism, Buddhism, Judaism, Christianity, Islam, and indigenous religions."),
    ("RELI202", "Christianity in The Bahamas", "School of Liberal and Fine Arts",
     "History and diversity of Christianity in Bahamian society; denominational traditions and social influence."),
    ("RELI203", "Religion and Society", "School of Liberal and Fine Arts",
     "The relationship between religion and society; secularisation, religious change, and public religion."),
    ("RELI301", "Caribbean Religions and Spirituality", "School of Liberal and Fine Arts",
     "African-derived religions, Revivalism, Rastafarianism, and other spiritual movements in the Caribbean."),

    # Humanities
    ("HUMA101", "Introduction to the Humanities", "School of Liberal and Fine Arts",
     "Interdisciplinary introduction to the arts and humanities; literature, music, visual arts, and philosophy."),
    ("HUMA201", "Arts and Culture of The Bahamas", "School of Liberal and Fine Arts",
     "Bahamian cultural identity as expressed through visual arts, music, literature, and performance."),
    ("HUMA301", "Caribbean Literature and Culture", "School of Liberal and Fine Arts",
     "Literary and cultural traditions of the Caribbean in a postcolonial context."),

    # Physical Education / Health
    ("PHED101", "Physical Education I", "School of Social and Educational Studies",
     "Foundations of physical education; fitness assessment, exercise principles, and lifetime wellness."),
    ("PHED102", "Physical Education II", "School of Social and Educational Studies",
     "Team sports, individual activities, and cooperative games; fitness development and sportsmanship."),
    ("PHED201", "Health and Wellness", "School of Social and Educational Studies",
     "Dimensions of wellness; nutrition, mental health, stress management, and disease prevention."),
    ("PHED202", "Sports and Recreation Management", "School of Social and Educational Studies",
     "Organisation and management of recreational and sporting programmes; facility management and event planning."),
    ("PHED301", "Kinesiology", "School of Social and Educational Studies",
     "Scientific study of human movement; biomechanics, exercise physiology, and sport psychology."),
    ("PHED302", "Coaching Principles", "School of Social and Educational Studies",
     "Philosophy, ethics, and techniques of sports coaching; athlete development and team leadership."),

    # ──────────────────────────────────────────────
    # SCHOOL OF BUSINESS — ADDITIONAL COURSES
    # ──────────────────────────────────────────────
    ("BADM101", "Introduction to Business", "School of Business",
     "Overview of the modern business environment; business functions, forms of ownership, and the Bahamian economy."),
    ("BADM301", "Business Law", "School of Business",
     "Legal environment of business; contracts, torts, property, agency, and business organisations under Bahamian law."),
    ("BADM302", "Business Ethics", "School of Business",
     "Ethical theories and their application to business decision-making; corporate social responsibility."),
    ("BADM401", "Strategic Management", "School of Business",
     "Formulation and implementation of competitive strategy; industry analysis, competitive advantage, and strategic planning."),
    ("BADM498", "Senior Thesis I: Business Administration", "School of Business",
     "Independent business research or consulting project; problem identification and research design."),
    ("BADM499", "Senior Thesis II: Business Administration", "School of Business",
     "Completion of the business research project; analysis, recommendations, and oral presentation."),

    ("ECON301", "Intermediate Microeconomics", "School of Business",
     "Advanced consumer theory, production theory, market structures, and general equilibrium."),
    ("ECON302", "Intermediate Macroeconomics", "School of Business",
     "Aggregate output, employment, inflation, monetary and fiscal policy, and open-economy macroeconomics."),
    ("ECON303", "Caribbean Economic Development", "School of Business",
     "Theories and empirical evidence on economic development; policies and challenges facing Caribbean economies."),
    ("ECON401", "Econometrics", "School of Business",
     "Statistical methods for economic analysis; regression, time series, and panel data econometrics."),
    ("ECON402", "International Economics", "School of Business",
     "International trade theory and policy; exchange rates, balance of payments, and global financial markets."),
    ("ECON403", "Public Finance", "School of Business",
     "Government expenditure, taxation, and fiscal policy; public goods, externalities, and social welfare."),
    ("ECON498", "Senior Thesis I: Economics", "School of Business",
     "Independent economics research project; literature review, data sources, and methodology."),
    ("ECON499", "Senior Thesis II: Economics", "School of Business",
     "Completion of the economics research project; econometric analysis, writing, and oral defence."),
]


class Command(BaseCommand):
    help = "Seed the database with University of The Bahamas course catalogue data (skips existing codes)."

    def handle(self, *args, **options):
        created = 0
        skipped = 0
        existing_codes = set(Course.objects.values_list("code", flat=True))

        for code, name, department, description in COURSES:
            if code in existing_codes:
                skipped += 1
                continue
            Course.objects.create(code=code, name=name, department=department, description=description)
            existing_codes.add(code)
            created += 1

        self.stdout.write(
            self.style.SUCCESS(
                f"Done. Created {created} new courses, skipped {skipped} already-existing codes."
            )
        )
