"""
Django management command: seed_ub_courses

Adds all University of The Bahamas courses that are not already in the
database (matched by course code). Department values are set to match the
School.name values already in the database so courses appear under the
correct school on the website.

Also corrects the department field on any existing courses that were
loaded with a wrong department name.

Safe to run multiple times.

Usage:
    python manage.py seed_ub_courses
"""

from django.core.management.base import BaseCommand

from professors.models import Course
from schools.models import College

# ── Department name constants (must match School.name exactly) ──────────────
BIZ = "School of Business"
COMM_ARTS = "School of Communication and Creative Arts"
ENGLISH = "School of English Studies"
CHEM_ENV_LIFE = "School of Chemistry, Environmental and Life Sciences"
MATH_PHYS_TECH = "School of Mathematics, Physics and Technology"
NURSING = "School of Nursing and Allied Health Professions"
EDUCATION = "School of Education"
SOCIAL_SCI = "School of Social Sciences"
TOURISM = "School of Tourism, Hospitality, Culinary Arts and Leisure Management"

COURSES = [
    # ── SCHOOL OF CHEMISTRY, ENVIRONMENTAL AND LIFE SCIENCES ─────────────────

    # Biology
    ("BIO102", "Introduction to Ecology", CHEM_ENV_LIFE,
     "An introduction to the principles of ecology, including population, community, and ecosystem dynamics with a Caribbean focus."),
    ("BIO201", "Cell Biology", CHEM_ENV_LIFE,
     "Study of cell structure, function, and metabolism, including molecular mechanisms of cell division and signalling."),
    ("BIO202", "Genetics", CHEM_ENV_LIFE,
     "Principles of heredity including Mendelian genetics, molecular genetics, gene regulation, and genomics."),
    ("BIO211", "Biology Laboratory I", CHEM_ENV_LIFE,
     "Laboratory exercises supporting Biology 101, covering microscopy, cell studies, and basic biological techniques."),
    ("BIO212", "Biology Laboratory II", CHEM_ENV_LIFE,
     "Laboratory exercises supporting Biology 102, covering field ecology, dissection, and experimental methods."),
    ("BIO301", "Microbiology", CHEM_ENV_LIFE,
     "Study of microorganisms including bacteria, viruses, fungi, and protozoa, with emphasis on their roles in health and the environment."),
    ("BIO302", "Ecology", CHEM_ENV_LIFE,
     "Relationships between organisms and their environments, energy flow, nutrient cycling, and conservation ecology."),
    ("BIO303", "Anatomy and Physiology I", CHEM_ENV_LIFE,
     "Structure and function of the human body: skeletal, muscular, nervous, and endocrine systems."),
    ("BIO304", "Anatomy and Physiology II", CHEM_ENV_LIFE,
     "Continuation of Anatomy and Physiology I: cardiovascular, respiratory, digestive, urinary, and reproductive systems."),
    ("BIO305", "Marine Biology", CHEM_ENV_LIFE,
     "Biology of marine organisms and ecosystems, with emphasis on the coastal and reef environments of The Bahamas."),
    ("BIO401", "Molecular Biology", CHEM_ENV_LIFE,
     "Advanced study of DNA replication, transcription, translation, and gene regulation at the molecular level."),
    ("BIO402", "Evolutionary Biology", CHEM_ENV_LIFE,
     "Mechanisms of evolution, including natural selection, genetic drift, speciation, and the history of life on Earth."),
    ("BIO403", "Immunology", CHEM_ENV_LIFE,
     "Structure and function of the immune system; innate and adaptive immunity; clinical applications."),
    ("BIO404", "Parasitology", CHEM_ENV_LIFE,
     "Biology, life cycles, and control of parasites of medical and veterinary importance in the Caribbean."),
    ("BIO498", "Senior Thesis I: Biology", CHEM_ENV_LIFE,
     "Independent research project under faculty supervision; literature review and research proposal."),
    ("BIO499", "Senior Thesis II: Biology", CHEM_ENV_LIFE,
     "Completion of the independent research project; data analysis, thesis writing, and oral presentation."),

    # Chemistry
    ("CHEM101", "General Chemistry I", CHEM_ENV_LIFE,
     "Principles of chemistry: atomic structure, chemical bonding, stoichiometry, gases, and thermochemistry."),
    ("CHEM102", "General Chemistry II", CHEM_ENV_LIFE,
     "Continuation of General Chemistry I: solutions, kinetics, equilibrium, acids and bases, electrochemistry."),
    ("CHEM111", "General Chemistry Laboratory I", CHEM_ENV_LIFE,
     "Laboratory exercises supporting General Chemistry I; qualitative and quantitative analysis techniques."),
    ("CHEM112", "General Chemistry Laboratory II", CHEM_ENV_LIFE,
     "Laboratory exercises supporting General Chemistry II; synthesis, titration, and spectroscopy."),
    ("CHEM201", "Organic Chemistry I", CHEM_ENV_LIFE,
     "Structure, properties, and reactions of organic compounds: alkanes, alkenes, alkynes, and aromatic compounds."),
    ("CHEM202", "Organic Chemistry II", CHEM_ENV_LIFE,
     "Continuation of Organic Chemistry I: carbonyl compounds, amines, polymers, carbohydrates, and spectroscopic analysis."),
    ("CHEM211", "Organic Chemistry Laboratory I", CHEM_ENV_LIFE,
     "Synthesis and characterisation of organic compounds using modern laboratory techniques."),
    ("CHEM212", "Organic Chemistry Laboratory II", CHEM_ENV_LIFE,
     "Advanced organic synthesis and spectroscopic identification of compounds."),
    ("CHEM301", "Analytical Chemistry", CHEM_ENV_LIFE,
     "Principles and methods of chemical analysis including gravimetry, titrimetry, and instrumental methods."),
    ("CHEM302", "Physical Chemistry I", CHEM_ENV_LIFE,
     "Thermodynamics, chemical equilibria, and electrochemistry from a physical chemistry perspective."),
    ("CHEM303", "Physical Chemistry II", CHEM_ENV_LIFE,
     "Quantum mechanics, spectroscopy, statistical mechanics, and reaction kinetics."),
    ("CHEM304", "Inorganic Chemistry", CHEM_ENV_LIFE,
     "Properties and reactions of inorganic compounds; coordination chemistry and organometallics."),
    ("CHEM401", "Biochemistry I", CHEM_ENV_LIFE,
     "Chemistry of biological macromolecules: proteins, nucleic acids, carbohydrates, and lipids."),
    ("CHEM402", "Biochemistry II", CHEM_ENV_LIFE,
     "Metabolism, enzyme kinetics, biosynthetic pathways, and molecular genetics from a biochemical viewpoint."),
    ("CHEM403", "Environmental Chemistry", CHEM_ENV_LIFE,
     "Chemistry of natural waters, atmosphere, and soils; pollution analysis and environmental remediation."),
    ("CHEM498", "Senior Thesis I: Chemistry", CHEM_ENV_LIFE,
     "Independent chemistry research project; literature review and experimental design."),
    ("CHEM499", "Senior Thesis II: Chemistry", CHEM_ENV_LIFE,
     "Completion of the chemistry research project; data analysis, thesis writing, and oral defence."),

    # Environmental Science
    ("ENVS101", "Introduction to Environmental Science", CHEM_ENV_LIFE,
     "Overview of Earth's natural systems and the human impacts on air, water, land, and biodiversity."),
    ("ENVS102", "Environmental Issues in The Bahamas", CHEM_ENV_LIFE,
     "Current environmental challenges facing The Bahamas: coastal erosion, coral bleaching, pollution, and climate change."),
    ("ENVS201", "Ecology", CHEM_ENV_LIFE,
     "Ecosystem structure and function, energy flow, nutrient cycles, population dynamics, and community ecology."),
    ("ENVS202", "Environmental Chemistry", CHEM_ENV_LIFE,
     "Chemical processes in the environment; fate and transport of pollutants in air, water, and soil."),
    ("ENVS301", "Conservation Biology", CHEM_ENV_LIFE,
     "Principles of conservation biology; biodiversity, habitat loss, invasive species, and protected areas management."),
    ("ENVS302", "Marine Ecology", CHEM_ENV_LIFE,
     "Ecology of marine ecosystems with emphasis on coral reefs, mangroves, and seagrass beds of The Bahamas."),
    ("ENVS303", "Environmental Policy and Law", CHEM_ENV_LIFE,
     "National and international environmental law and policy frameworks; Bahamian environmental legislation."),
    ("ENVS304", "Geographic Information Systems", CHEM_ENV_LIFE,
     "Introduction to GIS software and spatial data analysis for environmental applications."),
    ("ENVS401", "Climate Change Science and Impacts", CHEM_ENV_LIFE,
     "The science of climate change, projected impacts on small island developing states, and adaptation strategies."),
    ("ENVS402", "Coastal and Island Ecosystems", CHEM_ENV_LIFE,
     "Structure, function, and management of coastal ecosystems unique to island environments."),
    ("ENVS403", "Environmental Impact Assessment", CHEM_ENV_LIFE,
     "Methods and procedures for assessing the environmental impact of development projects."),
    ("ENVS498", "Senior Thesis I: Environmental Science", CHEM_ENV_LIFE,
     "Independent environmental research project; proposal development and literature review."),
    ("ENVS499", "Senior Thesis II: Environmental Science", CHEM_ENV_LIFE,
     "Completion of the environmental research project; field work, analysis, and thesis writing."),

    # Marine Science
    ("MARS101", "Introduction to Marine Science", CHEM_ENV_LIFE,
     "Overview of the marine environment: ocean chemistry, physical oceanography, and marine organisms."),
    ("MARS201", "Marine Biology", CHEM_ENV_LIFE,
     "Diversity, physiology, and ecology of marine organisms from phytoplankton to marine mammals."),
    ("MARS202", "Oceanography", CHEM_ENV_LIFE,
     "Physical, chemical, geological, and biological oceanography; ocean circulation and climate."),
    ("MARS301", "Coral Reef Ecology", CHEM_ENV_LIFE,
     "Structure, function, biodiversity, and conservation of coral reef ecosystems in the Caribbean."),
    ("MARS302", "Fisheries Science", CHEM_ENV_LIFE,
     "Fish biology, population dynamics, stock assessment, and sustainable fisheries management."),
    ("MARS303", "Marine Conservation", CHEM_ENV_LIFE,
     "Threats to marine biodiversity and strategies for conservation, including marine protected areas."),
    ("MARS498", "Senior Thesis I: Marine Science", CHEM_ENV_LIFE,
     "Independent marine science research; proposal, literature review, and research design."),
    ("MARS499", "Senior Thesis II: Marine Science", CHEM_ENV_LIFE,
     "Completion of the marine science research project; data collection, analysis, and thesis defence."),

    # ── SCHOOL OF MATHEMATICS, PHYSICS AND TECHNOLOGY ────────────────────────

    # Physics
    ("PHYS101", "General Physics I", MATH_PHYS_TECH,
     "Mechanics, kinematics, Newton's laws, work and energy, momentum, and rotational motion."),
    ("PHYS102", "General Physics II", MATH_PHYS_TECH,
     "Waves, sound, heat, thermodynamics, electricity, magnetism, and optics."),
    ("PHYS111", "General Physics Laboratory I", MATH_PHYS_TECH,
     "Laboratory experiments supporting General Physics I; measurement, motion, and energy."),
    ("PHYS112", "General Physics Laboratory II", MATH_PHYS_TECH,
     "Laboratory experiments supporting General Physics II; electricity, circuits, waves, and optics."),
    ("PHYS201", "Modern Physics", MATH_PHYS_TECH,
     "Relativity, quantum mechanics, atomic and nuclear physics, and an introduction to particle physics."),
    ("PHYS301", "Classical Mechanics", MATH_PHYS_TECH,
     "Newtonian mechanics, Lagrangian and Hamiltonian formulations, oscillations, and rigid body dynamics."),
    ("PHYS302", "Electromagnetism", MATH_PHYS_TECH,
     "Maxwell's equations, electric and magnetic fields, electromagnetic waves, and radiation."),
    ("PHYS303", "Thermodynamics and Statistical Mechanics", MATH_PHYS_TECH,
     "Laws of thermodynamics, entropy, statistical ensembles, and applications to physical systems."),
    ("PHYS401", "Quantum Mechanics", MATH_PHYS_TECH,
     "Wave functions, the Schrödinger equation, quantum operators, angular momentum, and the hydrogen atom."),
    ("PHYS402", "Optics", MATH_PHYS_TECH,
     "Geometrical and physical optics, interference, diffraction, polarisation, and laser physics."),
    ("PHYS498", "Senior Thesis I: Physics", MATH_PHYS_TECH,
     "Independent physics research project; literature review and experimental or computational design."),
    ("PHYS499", "Senior Thesis II: Physics", MATH_PHYS_TECH,
     "Completion of the physics research project; analysis, writing, and oral defence."),

    # Statistics
    ("STAT201", "Introduction to Statistics", MATH_PHYS_TECH,
     "Descriptive statistics, probability, sampling distributions, hypothesis testing, and regression."),
    ("STAT202", "Probability and Statistics", MATH_PHYS_TECH,
     "Probability theory, random variables, distributions, and statistical inference."),
    ("STAT301", "Statistical Methods", MATH_PHYS_TECH,
     "Advanced statistical techniques: analysis of variance, non-parametric tests, and experimental design."),
    ("STAT302", "Regression Analysis", MATH_PHYS_TECH,
     "Simple and multiple regression, model diagnostics, variable selection, and logistic regression."),
    ("STAT401", "Mathematical Statistics", MATH_PHYS_TECH,
     "Theoretical foundations of statistical inference: estimation, hypothesis testing, and Bayesian methods."),
    ("STAT402", "Applied Statistics", MATH_PHYS_TECH,
     "Statistical computing, data analysis, and interpretation using modern statistical software."),

    # More Computer Science
    ("CS301", "Algorithms and Data Structures", MATH_PHYS_TECH,
     "Design and analysis of algorithms; sorting, searching, graph algorithms, and computational complexity."),
    ("CS302", "Computer Organization and Architecture", MATH_PHYS_TECH,
     "Digital logic, computer organisation, instruction sets, memory hierarchy, and I/O systems."),
    ("CS303", "Operating Systems", MATH_PHYS_TECH,
     "Process management, memory management, file systems, I/O, and concurrent programming."),
    ("CS304", "Database Systems", MATH_PHYS_TECH,
     "Relational database design, SQL, normalisation, query optimisation, and transaction management."),
    ("CS305", "Computer Networks", MATH_PHYS_TECH,
     "Network architecture, protocols, TCP/IP, routing, security, and wireless networks."),
    ("CS401", "Software Engineering", MATH_PHYS_TECH,
     "Software development lifecycle, requirements, design patterns, testing, and project management."),
    ("CS402", "Artificial Intelligence", MATH_PHYS_TECH,
     "Search algorithms, knowledge representation, machine learning, natural language processing, and robotics."),
    ("CS403", "Web Development", MATH_PHYS_TECH,
     "Modern web technologies: HTML, CSS, JavaScript, front-end frameworks, back-end APIs, and databases."),
    ("CS404", "Cybersecurity", MATH_PHYS_TECH,
     "Information security principles, cryptography, network security, ethical hacking, and security management."),
    ("CS498", "Senior Thesis I: Computer Science", MATH_PHYS_TECH,
     "Individual software development or research project; requirements gathering, design, and implementation planning."),
    ("CS499", "Senior Thesis II: Computer Science", MATH_PHYS_TECH,
     "Completion of the senior software project; implementation, testing, documentation, and presentation."),

    # More Mathematics
    ("MAT102", "Calculus II", MATH_PHYS_TECH,
     "Integration techniques, applications of integration, sequences, series, and polar coordinates."),
    ("MAT201", "Calculus III", MATH_PHYS_TECH,
     "Multivariable calculus: partial derivatives, multiple integrals, vector calculus, and the theorems of Green, Stokes, and Gauss."),
    ("MAT202", "Linear Algebra", MATH_PHYS_TECH,
     "Vectors, matrices, systems of equations, determinants, eigenvalues, and vector spaces."),
    ("MAT301", "Differential Equations", MATH_PHYS_TECH,
     "Ordinary differential equations, Laplace transforms, series solutions, and systems of ODEs."),
    ("MAT302", "Discrete Mathematics", MATH_PHYS_TECH,
     "Logic, sets, functions, relations, combinatorics, graph theory, and mathematical proof techniques."),
    ("MAT303", "Number Theory", MATH_PHYS_TECH,
     "Divisibility, prime numbers, congruences, Diophantine equations, and cryptographic applications."),
    ("MAT401", "Abstract Algebra", MATH_PHYS_TECH,
     "Groups, rings, fields, homomorphisms, and an introduction to Galois theory."),
    ("MAT402", "Real Analysis", MATH_PHYS_TECH,
     "Rigorous treatment of limits, continuity, differentiation, integration, and sequences of functions."),
    ("MAT403", "Numerical Methods", MATH_PHYS_TECH,
     "Numerical solutions to equations, interpolation, numerical integration and differentiation, and ODEs."),
    ("MAT404", "Probability Theory", MATH_PHYS_TECH,
     "Axiomatic probability, random variables, expectation, distributions, and limit theorems."),
    ("MAT498", "Senior Thesis I: Mathematics", MATH_PHYS_TECH,
     "Independent mathematics research project; topic selection, literature review, and outline."),
    ("MAT499", "Senior Thesis II: Mathematics", MATH_PHYS_TECH,
     "Completion of the mathematics research project; proof development, writing, and oral defence."),

    # ── SCHOOL OF NURSING AND ALLIED HEALTH PROFESSIONS ──────────────────────
    ("NURS101", "Foundations of Nursing", NURSING,
     "Nursing history, philosophy, and professional values; basic nursing care concepts and health assessment."),
    ("NURS102", "Nursing Theory and Conceptual Models", NURSING,
     "Major nursing theories and conceptual frameworks that guide professional practice."),
    ("NURS111", "Nursing Skills Laboratory I", NURSING,
     "Hands-on practice of fundamental nursing skills: vital signs, hygiene, medication administration basics."),
    ("NURS112", "Nursing Skills Laboratory II", NURSING,
     "Advanced nursing skills: IV therapy, wound care, catheterisation, and sterile technique."),
    ("NURS201", "Adult Health Nursing I", NURSING,
     "Nursing care of adults with common medical-surgical conditions; pathophysiology and evidence-based interventions."),
    ("NURS202", "Adult Health Nursing II", NURSING,
     "Nursing care of adults with complex medical-surgical and critical conditions."),
    ("NURS203", "Mental Health Nursing", NURSING,
     "Psychiatric nursing principles; therapeutic communication, psychopharmacology, and care of patients with mental illness."),
    ("NURS204", "Pediatric Nursing", NURSING,
     "Nursing care of infants, children, and adolescents; growth, development, and family-centred care."),
    ("NURS205", "Pharmacology for Nurses", NURSING,
     "Drug classifications, mechanisms of action, therapeutic uses, adverse effects, and nursing implications."),
    ("NURS206", "Pathophysiology", NURSING,
     "Mechanisms of disease and altered physiological processes as a foundation for clinical nursing practice."),
    ("NURS301", "Maternal-Newborn Nursing", NURSING,
     "Nursing care during pregnancy, labour, delivery, and the postpartum period; newborn assessment and care."),
    ("NURS302", "Community Health Nursing", NURSING,
     "Population-focused nursing; epidemiology, health promotion, and community health assessment in The Bahamas."),
    ("NURS303", "Nursing Leadership and Management", NURSING,
     "Leadership theories, team management, delegation, and quality improvement in nursing practice."),
    ("NURS304", "Nursing Research", NURSING,
     "Evidence-based nursing practice; critical appraisal of research, research design, and application to clinical care."),
    ("NURS401", "Advanced Health Assessment", NURSING,
     "Comprehensive physical examination, diagnostic reasoning, and health history for complex patient presentations."),
    ("NURS402", "Gerontological Nursing", NURSING,
     "Nursing care of older adults; physiological changes of ageing, geriatric syndromes, and end-of-life care."),
    ("NURS403", "Clinical Practicum I", NURSING,
     "Supervised clinical placement in an acute care facility; application of nursing skills and theory."),
    ("NURS404", "Clinical Practicum II", NURSING,
     "Advanced supervised clinical placement across multiple specialities; professional role development."),
    ("NURS405", "Clinical Practicum III", NURSING,
     "Senior-level clinical practicum; leadership, case management, and preceptored practice."),
    ("NURS498", "Senior Thesis I: Nursing", NURSING,
     "Evidence-based capstone project; clinical question formulation, literature review, and proposal."),
    ("NURS499", "Senior Thesis II: Nursing", NURSING,
     "Completion of the nursing capstone project; data collection, analysis, and oral presentation."),

    # ── SCHOOL OF EDUCATION ──────────────────────────────────────────────────
    ("EDUC101", "Introduction to Education", EDUCATION,
     "Overview of education as a profession; history, philosophy, and organisation of education in The Bahamas."),
    ("EDUC201", "Educational Psychology", EDUCATION,
     "Psychological principles applied to teaching and learning; motivation, development, and learning theories."),
    ("EDUC202", "Curriculum Development", EDUCATION,
     "Principles and practices of curriculum design, implementation, and evaluation for Bahamian schools."),
    ("EDUC203", "Teaching Methods: Secondary", EDUCATION,
     "Strategies and techniques for effective teaching in secondary school settings."),
    ("EDUC204", "Teaching Methods: Primary", EDUCATION,
     "Pedagogy, classroom management, and instructional strategies for primary school teachers."),
    ("EDUC205", "Foundations of Early Childhood Education", EDUCATION,
     "Developmental theory, curriculum, and best practices for teaching children aged birth to eight years."),
    ("EDUC301", "Assessment and Evaluation", EDUCATION,
     "Principles of classroom and programme assessment; formative and summative evaluation strategies."),
    ("EDUC302", "Special Education", EDUCATION,
     "Identification, assessment, and instructional strategies for students with diverse learning needs."),
    ("EDUC303", "Classroom Management", EDUCATION,
     "Strategies for creating and maintaining positive, productive learning environments."),
    ("EDUC304", "Inclusive Education", EDUCATION,
     "Principles and practices of inclusive schooling; diversity, differentiation, and collaboration."),
    ("EDUC401", "Educational Leadership", EDUCATION,
     "Leadership theories and practices for school administrators; school culture and change management."),
    ("EDUC402", "Education Policy", EDUCATION,
     "Analysis of national and regional education policy; education reform and governance in The Bahamas."),
    ("EDUC403", "Educational Technology", EDUCATION,
     "Integration of technology into classroom instruction; digital tools, e-learning, and media literacy."),
    ("EDUC404", "Student Teaching Practicum", EDUCATION,
     "Supervised teaching experience in an accredited school; observation, co-teaching, and solo teaching."),
    ("EDUC498", "Senior Thesis I: Education", EDUCATION,
     "Independent education research project; action research design and literature review."),
    ("EDUC499", "Senior Thesis II: Education", EDUCATION,
     "Completion of the education research project; data collection, analysis, and presentation."),

    # Physical Education (also under Education)
    ("PHED101", "Physical Education I", EDUCATION,
     "Foundations of physical education; fitness assessment, exercise principles, and lifetime wellness."),
    ("PHED102", "Physical Education II", EDUCATION,
     "Team sports, individual activities, and cooperative games; fitness development and sportsmanship."),
    ("PHED201", "Health and Wellness", EDUCATION,
     "Dimensions of wellness; nutrition, mental health, stress management, and disease prevention."),
    ("PHED202", "Sports and Recreation Management", EDUCATION,
     "Organisation and management of recreational and sporting programmes; facility management and event planning."),
    ("PHED301", "Kinesiology", EDUCATION,
     "Scientific study of human movement; biomechanics, exercise physiology, and sport psychology."),
    ("PHED302", "Coaching Principles", EDUCATION,
     "Philosophy, ethics, and techniques of sports coaching; athlete development and team leadership."),

    # ── SCHOOL OF SOCIAL SCIENCES ─────────────────────────────────────────────

    # Psychology
    ("PSYC101", "Introduction to Psychology", SOCIAL_SCI,
     "Survey of psychology's major subfields: biological bases of behaviour, learning, cognition, development, personality, and social psychology."),
    ("PSYC102", "Research Methods in Psychology", SOCIAL_SCI,
     "Scientific method in psychology; experimental and non-experimental designs, statistics, and ethical guidelines."),
    ("PSYC201", "Developmental Psychology", SOCIAL_SCI,
     "Human development from conception through old age, including cognitive, social, and emotional development."),
    ("PSYC202", "Abnormal Psychology", SOCIAL_SCI,
     "Classification, causes, and treatment of psychological disorders; DSM framework and therapeutic approaches."),
    ("PSYC203", "Social Psychology", SOCIAL_SCI,
     "How thoughts, feelings, and behaviours are influenced by others; attitudes, conformity, aggression, and helping."),
    ("PSYC204", "Biological Psychology", SOCIAL_SCI,
     "Neuroanatomy, neurotransmitters, and the biological bases of behaviour, emotion, and mental disorders."),
    ("PSYC301", "Cognitive Psychology", SOCIAL_SCI,
     "Mental processes involved in perception, attention, memory, language, thinking, and problem solving."),
    ("PSYC302", "Personality Psychology", SOCIAL_SCI,
     "Major theories of personality; trait, psychodynamic, humanistic, and social-cognitive approaches."),
    ("PSYC303", "Health Psychology", SOCIAL_SCI,
     "Psychological factors in health and illness; stress, coping, chronic disease, and health promotion."),
    ("PSYC304", "Counselling Theories", SOCIAL_SCI,
     "Major theories and approaches in professional counselling; person-centred, CBT, and psychodynamic models."),
    ("PSYC305", "Industrial/Organisational Psychology", SOCIAL_SCI,
     "Application of psychological principles to the workplace: selection, motivation, leadership, and organisational behaviour."),
    ("PSYC306", "Community Psychology", SOCIAL_SCI,
     "Psychological perspectives on community life, prevention, empowerment, and social change."),
    ("PSYC401", "Advanced Research Methods", SOCIAL_SCI,
     "Advanced quantitative and qualitative research designs, multi-variate analysis, and research ethics."),
    ("PSYC402", "Psychological Assessment", SOCIAL_SCI,
     "Principles of psychological testing; intelligence, personality, and neuropsychological assessments."),
    ("PSYC498", "Senior Thesis I: Psychology", SOCIAL_SCI,
     "Independent psychological research project; topic selection, literature review, and methodology."),
    ("PSYC499", "Senior Thesis II: Psychology", SOCIAL_SCI,
     "Completion of the psychology research project; data collection, analysis, write-up, and presentation."),

    # Sociology
    ("SOCI101", "Introduction to Sociology", SOCIAL_SCI,
     "Sociological perspectives on social structure, culture, socialisation, stratification, and social change."),
    ("SOCI102", "Social Problems", SOCIAL_SCI,
     "Analysis of major social problems in The Bahamas and the Caribbean: poverty, crime, inequality, and discrimination."),
    ("SOCI201", "Cultural Anthropology", SOCIAL_SCI,
     "Introduction to cultural anthropology: culture, kinship, religion, economic systems, and globalisation."),
    ("SOCI202", "Caribbean Sociology", SOCIAL_SCI,
     "Social structures and processes unique to the Caribbean; slavery's legacy, identity, and development challenges."),
    ("SOCI203", "Race, Ethnicity, and Society", SOCIAL_SCI,
     "Sociological analysis of race and ethnicity; prejudice, discrimination, and multicultural societies."),
    ("SOCI204", "Gender and Society", SOCIAL_SCI,
     "Gender as a social construct; gender roles, feminism, masculinity, and gender-based inequality."),
    ("SOCI301", "Sociological Theory", SOCIAL_SCI,
     "Classical and contemporary sociological theory: Marx, Weber, Durkheim, Parsons, and contemporary theorists."),
    ("SOCI302", "Research Methods in Sociology", SOCIAL_SCI,
     "Quantitative and qualitative research methods; surveys, interviews, ethnography, and content analysis."),
    ("SOCI303", "Sociology of the Family", SOCIAL_SCI,
     "Family structures, roles, and dynamics; marriage, divorce, parenting, and family policy."),
    ("SOCI304", "Deviance and Social Control", SOCIAL_SCI,
     "Theories of deviant behaviour; crime, stigma, and social control mechanisms."),
    ("SOCI401", "Social Stratification", SOCIAL_SCI,
     "Systems of inequality: class, status, and power; social mobility in the Caribbean context."),
    ("SOCI402", "Urban Sociology", SOCIAL_SCI,
     "Urban social structures, community life, urbanisation, and development in the Caribbean."),
    ("SOCI403", "Sociology of Religion", SOCIAL_SCI,
     "The social dimensions of religion; religious institutions, movements, and religion's role in Caribbean society."),
    ("SOCI498", "Senior Thesis I: Sociology", SOCIAL_SCI,
     "Independent sociological research project; research question formulation, literature review, and methodology."),
    ("SOCI499", "Senior Thesis II: Sociology", SOCIAL_SCI,
     "Completion of the sociology research project; fieldwork, data analysis, and thesis writing."),

    # Political Science
    ("POLI101", "Introduction to Political Science", SOCIAL_SCI,
     "Foundations of political science; political systems, ideologies, institutions, and political behaviour."),
    ("POLI102", "Introduction to Political Thought", SOCIAL_SCI,
     "History of political philosophy from the ancient Greeks to the modern era."),
    ("POLI201", "Bahamian Government and Politics", SOCIAL_SCI,
     "The Constitution, Parliament, the executive, the judiciary, and political parties of The Bahamas."),
    ("POLI202", "Caribbean Politics", SOCIAL_SCI,
     "Political systems and governance challenges across the Caribbean; CARICOM and regional integration."),
    ("POLI203", "International Relations", SOCIAL_SCI,
     "Theories and issues in international relations; diplomacy, international organisations, and global governance."),
    ("POLI204", "Comparative Politics", SOCIAL_SCI,
     "Comparative analysis of political systems, elections, parties, and democratic institutions worldwide."),
    ("POLI301", "Political Theory", SOCIAL_SCI,
     "Normative political theory: justice, liberty, equality, democracy, and rights."),
    ("POLI302", "Research Methods in Political Science", SOCIAL_SCI,
     "Quantitative and qualitative research design for political analysis; surveys, case studies, and statistical methods."),
    ("POLI303", "Public Administration", SOCIAL_SCI,
     "Principles of public administration; bureaucracy, public policy implementation, and government management."),
    ("POLI304", "Public Policy", SOCIAL_SCI,
     "Policy-making processes; agenda-setting, policy design, implementation, and evaluation."),
    ("POLI401", "Global Politics", SOCIAL_SCI,
     "Globalisation, global governance, transnational actors, and emerging issues in world politics."),
    ("POLI402", "Caribbean Foreign Policy", SOCIAL_SCI,
     "Foreign policy challenges of small Caribbean states; bilateral and multilateral relations."),
    ("POLI498", "Senior Thesis I: Political Science", SOCIAL_SCI,
     "Independent political science research project; topic selection, literature review, and methodology."),
    ("POLI499", "Senior Thesis II: Political Science", SOCIAL_SCI,
     "Completion of the political science research project; analysis, writing, and oral defence."),

    # History
    ("HIST101", "History of The Bahamas", SOCIAL_SCI,
     "The Bahamas from the Lucayan era through colonial rule, emancipation, independence, and nationhood."),
    ("HIST102", "Caribbean History", SOCIAL_SCI,
     "History of the Caribbean from indigenous peoples through colonialism, slavery, emancipation, and independence."),
    ("HIST201", "World History to 1500", SOCIAL_SCI,
     "Major developments in human civilisation from ancient times through the late medieval period."),
    ("HIST202", "World History from 1500", SOCIAL_SCI,
     "Global history from the Age of Exploration through the twentieth century; colonialism, revolution, and globalisation."),
    ("HIST203", "African History", SOCIAL_SCI,
     "History of Africa from ancient kingdoms through colonialism, independence, and contemporary challenges."),
    ("HIST204", "British History", SOCIAL_SCI,
     "Political, social, and cultural history of Britain and its relationship with its colonies."),
    ("HIST205", "American History", SOCIAL_SCI,
     "United States history from colonial origins through the twenty-first century; its impact on the Caribbean."),
    ("HIST301", "Slavery and Emancipation in the Caribbean", SOCIAL_SCI,
     "The transatlantic slave trade, plantation society, abolition, and the aftermath of emancipation."),
    ("HIST302", "The Atlantic World", SOCIAL_SCI,
     "Interconnections among Europe, Africa, and the Americas in the age of exploration and colonialism."),
    ("HIST303", "Social History of The Bahamas", SOCIAL_SCI,
     "Social life, culture, labour, religion, and everyday experience in Bahamian history."),
    ("HIST401", "Historiography", SOCIAL_SCI,
     "Theory and methodology of historical research; how historians write history."),
    ("HIST402", "Historical Research Methods", SOCIAL_SCI,
     "Archival research, oral history, use of primary sources, and historical writing."),
    ("HIST498", "Senior Thesis I: History", SOCIAL_SCI,
     "Independent history research project; archival research, literature review, and thesis outline."),
    ("HIST499", "Senior Thesis II: History", SOCIAL_SCI,
     "Completion of the history thesis; research, analysis, writing, and oral defence."),

    # Social Work
    ("SOWK101", "Introduction to Social Work", SOCIAL_SCI,
     "History, values, ethics, and scope of the social work profession; social welfare in The Bahamas."),
    ("SOWK201", "Human Behaviour and the Social Environment", SOCIAL_SCI,
     "Systems and ecological theories applied to individual, family, group, and community behaviour."),
    ("SOWK202", "Social Welfare Policy", SOCIAL_SCI,
     "Development and analysis of social welfare policy and its impact on vulnerable populations in the Caribbean."),
    ("SOWK301", "Social Work Practice I: Individuals and Families", SOCIAL_SCI,
     "Generalist social work skills for working with individuals and families; assessment, planning, and intervention."),
    ("SOWK302", "Social Work Practice II: Groups and Communities", SOCIAL_SCI,
     "Group work theory and community organisation practice; facilitating change at the macro level."),
    ("SOWK303", "Social Work Research Methods", SOCIAL_SCI,
     "Research design and evidence-based practice in social work; quantitative, qualitative, and mixed methods."),
    ("SOWK401", "Child Welfare", SOCIAL_SCI,
     "Child protection systems, family preservation, foster care, and adoption policies in The Bahamas."),
    ("SOWK402", "Field Practicum I", SOCIAL_SCI,
     "Supervised field placement in a social service agency; application of theory to practice."),
    ("SOWK403", "Field Practicum II", SOCIAL_SCI,
     "Advanced supervised field placement with increased responsibility and reflective practice seminars."),
    ("SOWK498", "Senior Thesis I: Social Work", SOCIAL_SCI,
     "Independent social work research or policy analysis project; proposal and literature review."),
    ("SOWK499", "Senior Thesis II: Social Work", SOCIAL_SCI,
     "Completion of the social work research project; analysis, writing, and oral defence."),

    # Criminology
    ("CRIM101", "Introduction to Criminology", SOCIAL_SCI,
     "Theories of crime and criminal behaviour; the nature and extent of crime in The Bahamas and the Caribbean."),
    ("CRIM201", "The Criminal Justice System", SOCIAL_SCI,
     "Structure and operation of the criminal justice system: police, courts, and corrections."),
    ("CRIM202", "Juvenile Delinquency", SOCIAL_SCI,
     "Causes and consequences of juvenile delinquency; youth crime prevention and the juvenile justice system."),
    ("CRIM301", "Policing", SOCIAL_SCI,
     "History, organisation, and practice of policing; community policing and law enforcement reform."),
    ("CRIM302", "Corrections", SOCIAL_SCI,
     "History and philosophy of punishment; incarceration, probation, parole, and rehabilitation programmes."),
    ("CRIM303", "Criminal Law", SOCIAL_SCI,
     "Principles of criminal law; elements of crimes, defences, and the Bahamian criminal justice process."),
    ("CRIM401", "Crime Prevention", SOCIAL_SCI,
     "Situational and social crime prevention strategies; evidence-based programmes for reducing crime."),
    ("CRIM402", "Research Methods in Criminology", SOCIAL_SCI,
     "Quantitative and qualitative research methods applied to criminological questions."),
    ("CRIM498", "Senior Thesis I: Criminology", SOCIAL_SCI,
     "Independent criminological research project; research question, literature review, and methodology."),
    ("CRIM499", "Senior Thesis II: Criminology", SOCIAL_SCI,
     "Completion of the criminology research project; data analysis, writing, and oral defence."),

    # Geography
    ("GEOG101", "Introduction to Human Geography", SOCIAL_SCI,
     "Human geography concepts: population, migration, cultural landscapes, urbanisation, and globalisation."),
    ("GEOG102", "Physical Geography", SOCIAL_SCI,
     "Earth's physical systems: atmosphere, hydrosphere, lithosphere, and biosphere; weather, climate, and landforms."),
    ("GEOG201", "Bahamian and Caribbean Geography", SOCIAL_SCI,
     "Physical and human geography of The Bahamas and the wider Caribbean region."),
    ("GEOG202", "Economic Geography", SOCIAL_SCI,
     "Spatial patterns of economic activity; trade, industry, agriculture, and regional development."),
    ("GEOG301", "Geographic Information Systems", SOCIAL_SCI,
     "GIS principles, spatial data analysis, and mapping for social science applications."),
    ("GEOG302", "Population Geography", SOCIAL_SCI,
     "Population distribution, growth, migration, and demographic change with a Caribbean focus."),
    ("GEOG498", "Senior Thesis I: Geography", SOCIAL_SCI,
     "Independent geography research project; topic selection, field methodology, and literature review."),
    ("GEOG499", "Senior Thesis II: Geography", SOCIAL_SCI,
     "Completion of the geography research project; mapping, analysis, and thesis writing."),

    # ── SCHOOL OF TOURISM, HOSPITALITY, CULINARY ARTS AND LEISURE MANAGEMENT ─
    ("TOUR101", "Introduction to Tourism", TOURISM,
     "Overview of the global tourism industry; tourism systems, stakeholders, and The Bahamas' tourism economy."),
    ("TOUR201", "Tourism Management", TOURISM,
     "Management principles applied to tourism enterprises; planning, organising, and leading tourism operations."),
    ("TOUR202", "Ecotourism", TOURISM,
     "Principles and practice of ecotourism; sustainable tourism development in natural and cultural environments."),
    ("TOUR301", "Tourism Marketing", TOURISM,
     "Marketing strategies for tourism destinations and businesses; consumer behaviour and digital marketing."),
    ("TOUR302", "Sustainable Tourism Development", TOURISM,
     "Frameworks for developing tourism that minimises environmental impact and maximises community benefit."),
    ("TOUR303", "Heritage and Cultural Tourism", TOURISM,
     "Tourism based on cultural and natural heritage; interpretation, authenticity, and community involvement."),
    ("TOUR401", "Tourism Policy and Planning", TOURISM,
     "National and regional tourism policy; destination planning, governance, and the role of government."),
    ("TOUR402", "Tourism Economics", TOURISM,
     "Economic analysis of tourism; tourism demand, supply, multipliers, and the Bahamian tourism economy."),
    ("TOUR498", "Senior Thesis I: Tourism", TOURISM,
     "Independent tourism research project; research design and literature review."),
    ("TOUR499", "Senior Thesis II: Tourism", TOURISM,
     "Completion of the tourism research project; fieldwork, analysis, and presentation."),

    # Hotel, Restaurant, and Spa Management
    ("HRSM101", "Introduction to Hospitality Management", TOURISM,
     "Overview of the hospitality industry; hotels, restaurants, and resorts in The Bahamas and the Caribbean."),
    ("HRSM201", "Front Office Operations", TOURISM,
     "Reservations, check-in/check-out procedures, property management systems, and guest relations."),
    ("HRSM202", "Housekeeping Management", TOURISM,
     "Organisation and management of housekeeping departments in hotels and resorts."),
    ("HRSM203", "Food and Beverage Management", TOURISM,
     "Operations management for restaurants and food service; cost control, menu planning, and service standards."),
    ("HRSM204", "Lodging Management", TOURISM,
     "Strategic management of hotel and resort operations; revenue management, staffing, and quality control."),
    ("HRSM205", "Event Management", TOURISM,
     "Planning, organising, and executing meetings, conferences, weddings, and special events."),
    ("HRSM301", "Hospitality Law", TOURISM,
     "Legal aspects of the hospitality industry; liability, contracts, consumer protection, and licensing."),
    ("HRSM302", "Hospitality Marketing", TOURISM,
     "Marketing strategies for hotels and resorts; branding, digital marketing, and loyalty programmes."),
    ("HRSM303", "Resort and Spa Management", TOURISM,
     "Operations and management of resort and spa facilities; guest experience and wellness programming."),
    ("HRSM401", "Revenue Management", TOURISM,
     "Demand forecasting, pricing strategies, and yield management for hospitality businesses."),
    ("HRSM402", "Hospitality Financial Management", TOURISM,
     "Financial analysis, budgeting, and cost control specific to hospitality operations."),
    ("HRSM498", "Senior Thesis I: Hospitality Management", TOURISM,
     "Independent hospitality research or industry project; proposal and literature review."),
    ("HRSM499", "Senior Thesis II: Hospitality Management", TOURISM,
     "Completion of the hospitality research project; analysis, writing, and oral presentation."),

    # Culinary Arts
    ("CULA101", "Culinary Arts Fundamentals", TOURISM,
     "Basic culinary skills: knife techniques, cooking methods, sanitation, and kitchen safety."),
    ("CULA201", "Culinary Techniques", TOURISM,
     "Intermediate cooking techniques; sauces, stocks, braising, roasting, and baking fundamentals."),
    ("CULA202", "Bahamian and Caribbean Cuisine", TOURISM,
     "History, ingredients, and techniques of Bahamian and Caribbean culinary traditions."),
    ("CULA301", "Pastry and Baking Arts", TOURISM,
     "Artisan bread, cakes, pastries, and confectionery; classical and modern baking techniques."),
    ("CULA302", "International Cuisine", TOURISM,
     "Culinary traditions from around the world; techniques, ingredients, and cultural context."),
    ("CULA401", "Food and Beverage Business Operations", TOURISM,
     "Running a successful food service business; menu costing, staffing, marketing, and entrepreneurship."),

    # ── SCHOOL OF COMMUNICATION AND CREATIVE ARTS (Theatre) ──────────────────
    ("THEA101", "Introduction to Theatre Arts", COMM_ARTS,
     "History, theory, and appreciation of theatre; reading plays and attending live performances."),
    ("THEA201", "Acting I", COMM_ARTS,
     "Fundamental acting techniques; voice, movement, characterisation, and scene study."),
    ("THEA202", "Stagecraft", COMM_ARTS,
     "Technical aspects of theatre production: set design, lighting, sound, and stage management."),
    ("THEA203", "Script Analysis", COMM_ARTS,
     "Analytical tools for reading and interpreting dramatic texts for performance."),
    ("THEA301", "Directing", COMM_ARTS,
     "Principles and practice of theatrical direction; script interpretation, staging, and rehearsal process."),
    ("THEA302", "Playwriting", COMM_ARTS,
     "Craft of writing for the stage; dramatic structure, dialogue, character, and the development of original work."),
    ("THEA303", "Caribbean Theatre and Performance", COMM_ARTS,
     "Theatre traditions and performance practices of the Caribbean; folk forms, carnival, and contemporary drama."),
    ("THEA401", "Advanced Acting", COMM_ARTS,
     "Advanced techniques in classical and contemporary performance styles."),
    ("THEA498", "Senior Thesis I: Theatre Arts", COMM_ARTS,
     "Independent theatre project or research; directing, writing, or historical study."),
    ("THEA499", "Senior Thesis II: Theatre Arts", COMM_ARTS,
     "Completion of the theatre arts project; public performance or written thesis and defence."),

    # ── SCHOOL OF ENGLISH STUDIES (Philosophy, Humanities, Religious Studies) ─
    ("PHIL101", "Introduction to Philosophy", ENGLISH,
     "Central questions of philosophy: knowledge, reality, ethics, and the meaning of existence."),
    ("PHIL102", "Critical Thinking and Logic", ENGLISH,
     "Principles of sound reasoning; argument analysis, logical fallacies, and formal and informal logic."),
    ("PHIL201", "Ethics", ENGLISH,
     "Normative ethical theories — utilitarianism, deontology, virtue ethics — and their application to moral problems."),
    ("PHIL202", "Philosophy of Religion", ENGLISH,
     "Philosophical analysis of religious belief; arguments for and against the existence of God; faith and reason."),
    ("PHIL203", "Political Philosophy", ENGLISH,
     "Philosophical foundations of political authority, justice, rights, democracy, and the social contract."),
    ("PHIL301", "Philosophy of Mind", ENGLISH,
     "The nature of mind and consciousness; dualism, physicalism, functionalism, and artificial intelligence."),
    ("PHIL302", "Epistemology", ENGLISH,
     "Theory of knowledge; the nature of belief, justification, truth, and scepticism."),
    ("PHIL401", "Metaphysics", ENGLISH,
     "Fundamental questions about reality: existence, identity, causation, space, and time."),
    ("RELI101", "Introduction to Religious Studies", ENGLISH,
     "Academic study of religion; methods, key concepts, and introduction to major world religions."),
    ("RELI201", "World Religions", ENGLISH,
     "Comparative study of Hinduism, Buddhism, Judaism, Christianity, Islam, and indigenous religions."),
    ("RELI202", "Christianity in The Bahamas", ENGLISH,
     "History and diversity of Christianity in Bahamian society; denominational traditions and social influence."),
    ("RELI301", "Caribbean Religions and Spirituality", ENGLISH,
     "African-derived religions, Revivalism, Rastafarianism, and other spiritual movements in the Caribbean."),
    ("HUMA101", "Introduction to the Humanities", ENGLISH,
     "Interdisciplinary introduction to the arts and humanities; literature, music, visual arts, and philosophy."),
    ("HUMA201", "Arts and Culture of The Bahamas", ENGLISH,
     "Bahamian cultural identity as expressed through visual arts, music, literature, and performance."),
    ("HUMA301", "Caribbean Literature and Culture", ENGLISH,
     "Literary and cultural traditions of the Caribbean in a postcolonial context."),

    # ── SCHOOL OF BUSINESS — ADDITIONAL COURSES ──────────────────────────────
    ("BADM101", "Introduction to Business", BIZ,
     "Overview of the modern business environment; business functions, forms of ownership, and the Bahamian economy."),
    ("BADM301", "Business Law", BIZ,
     "Legal environment of business; contracts, torts, property, agency, and business organisations under Bahamian law."),
    ("BADM302", "Business Ethics", BIZ,
     "Ethical theories and their application to business decision-making; corporate social responsibility."),
    ("BADM401", "Strategic Management", BIZ,
     "Formulation and implementation of competitive strategy; industry analysis, competitive advantage, and strategic planning."),
    ("ECON301", "Intermediate Microeconomics", BIZ,
     "Advanced consumer theory, production theory, market structures, and general equilibrium."),
    ("ECON302", "Intermediate Macroeconomics", BIZ,
     "Aggregate output, employment, inflation, monetary and fiscal policy, and open-economy macroeconomics."),
    ("ECON303", "Caribbean Economic Development", BIZ,
     "Theories and empirical evidence on economic development; policies and challenges facing Caribbean economies."),
    ("ECON401", "Econometrics", BIZ,
     "Statistical methods for economic analysis; regression, time series, and panel data econometrics."),
    ("ECON402", "International Economics", BIZ,
     "International trade theory and policy; exchange rates, balance of payments, and global financial markets."),
    ("ECON403", "Public Finance", BIZ,
     "Government expenditure, taxation, and fiscal policy; public goods, externalities, and social welfare."),
    ("ECON498", "Senior Thesis I: Economics", BIZ,
     "Independent economics research project; literature review, data sources, and methodology."),
    ("ECON499", "Senior Thesis II: Economics", BIZ,
     "Completion of the economics research project; econometric analysis, writing, and oral defence."),
]

# Existing courses that were loaded with wrong department names — fix them.
DEPARTMENT_CORRECTIONS = {
    "Biology": CHEM_ENV_LIFE,
    "Computer Science": MATH_PHYS_TECH,
    "Mathematics": MATH_PHYS_TECH,
}

# College names that need updating to match the official UB catalogue.
COLLEGE_NAME_CORRECTIONS = {
    "Business": "College of Business",
    "Liberal & Fine Arts": "College of Liberal and Fine Arts",
    "Pure & Applied Sciences": "College of Pure and Applied Sciences",
    "Social & Educational Studies": "College of Social and Educational Studies",
    "Tourism, Hospitality, Culinary Arts & Leisure Management": "College of Tourism, Hospitality, Culinary Arts and Leisure Management",
}


class Command(BaseCommand):
    help = "Seed the database with UB course catalogue data and fix any wrong department names."

    def handle(self, *args, **options):
        # ── Fix College names to match the official UB catalogue ───────────
        for old_name, new_name in COLLEGE_NAME_CORRECTIONS.items():
            count = College.objects.filter(name=old_name).update(name=new_name)
            if count:
                self.stdout.write(f"  Fixed college name: '{old_name}' → '{new_name}'")

        # ── Fix existing courses with wrong department names ────────────────
        fixed = 0
        for old_dept, new_dept in DEPARTMENT_CORRECTIONS.items():
            count = Course.objects.filter(department=old_dept).update(department=new_dept)
            if count:
                self.stdout.write(f"  Fixed {count} course(s): '{old_dept}' → '{new_dept}'")
                fixed += count

        # ── Insert new courses (skip existing codes) ───────────────────────
        existing_codes = set(Course.objects.values_list("code", flat=True))
        created = 0
        skipped = 0

        for code, name, department, description in COURSES:
            if code in existing_codes:
                skipped += 1
                continue
            Course.objects.create(code=code, name=name, department=department, description=description)
            existing_codes.add(code)
            created += 1

        self.stdout.write(
            self.style.SUCCESS(
                f"Done. Created {created} new courses, fixed {fixed} department names, "
                f"skipped {skipped} already-existing codes."
            )
        )
