# Generated by Django 6.0.6 on 2026-06-26 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='department',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='professor',
            name='department',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='professor',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
