# Generated by Django 6.0.6 on 2026-06-26 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0002_alter_course_department_alter_course_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
