# Generated by Django 6.0.6 on 2026-06-26 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0003_course_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='would_take_again',
            field=models.BooleanField(default=True),
        ),
    ]
