# Generated by Django 6.0.6 on 2026-06-26 01:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0004_review_would_take_again'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessorCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professor_courses', to='professors.course')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professor_courses', to='professors.professor')),
            ],
            options={
                'unique_together': {('professor', 'course')},
            },
        ),
    ]
