# Generated by Django 6.0.6 on 2026-06-26 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0005_professorcourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='uses_textbook',
            field=models.BooleanField(default=False),
        ),
    ]
