# Generated by Django 6.0.6 on 2026-06-26 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0006_review_uses_textbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='professorcourse',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
