# Generated by Django 6.0.6 on 2026-06-29 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0007_professorcourse_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
